import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../src/styles.css',import.meta.url),'utf8');
const app=fs.readFileSync(new URL('../src/app.js',import.meta.url),'utf8');
const chart=fs.readFileSync(new URL('../src/chart.js',import.meta.url),'utf8');
const cap=JSON.parse(fs.readFileSync(new URL('../capacitor.config.json',import.meta.url),'utf8'));
for(const id of ['mobileChartBar','mobileBottomNav','mobileMoreSheet','mobileDrawButton','mobileMoreQuick','mobileTimeframeSelect','mobileSymbolQuick','mobileSurfaceBackdrop']) assert.match(html,new RegExp(`id=["']${id}["']`),`missing ${id}`);
for(const action of ['indicators','alerts','replay','objects','chart','scripts','backtest','paper','settings','fit','share']) assert.match(html,new RegExp(`data-mobile-action=["']${action}["']`),`missing mobile action ${action}`);
for(const nav of ['watchlist','chart','scanner','scripts','more']) assert.match(html,new RegExp(`data-mobile-nav=["']${nav}["']`),`missing mobile nav ${nav}`);
assert.match(css,/html,body,#app\{position:fixed;inset:0[^}]*overflow:hidden!important/, 'mobile page must be fixed and non-scrollable');
assert.match(css,/--mobile-bottom-stack:calc\(var\(--mobile-nav-h\) \+ var\(--mobile-action-h\) \+ var\(--safe-bottom\)\)/, 'mobile bottom stack variable missing');
assert.match(css,/\.workspace-shell\{[\s\S]*?inset:0 0 var\(--mobile-bottom-stack\) 0!important/, 'chart viewport must end above controls');
assert.match(css,/\.mobile-chart-bar\{[\s\S]*?position:fixed/, 'chart action bar must be fixed');
assert.match(css,/\.mobile-bottom-nav\{[\s\S]*?position:fixed/, 'bottom navigation must be fixed');
assert.match(css,/#mobileShareButton,#mobileFitButton\{display:none!important\}/, 'low-frequency actions should not crowd chart bar');
assert.match(css,/\.tool-rail\.mobile-sheet-open\{display:grid!important/, 'drawing tools must open as a sheet');
assert.match(app,/mobileDrawButton[^\n]+openMobileSurface\('tools'\)/, 'pen must open drawing sheet');
assert.match(app,/mobileMoreQuick[^\n]+openMobileSurface\('more'\)/, 'three dots must open analysis sheet');
assert.match(app,/n==='more'\)return openMobileSurface\('more'\)/, 'bottom More button must open analysis sheet');
assert.match(app,/bindSheetDrag/, 'sheets must support drag-to-dismiss');
assert.match(chart,/const mobile=this\.width<=520,area=clamp\(this\.mainBottom\*\(mobile\?\.145:\.18\)/, 'mobile volume overlay should have dedicated visible area');
assert.equal(cap.ios?.contentInset,'never','iOS must not add native safe-area inset on top of CSS safe areas');
const ids=[...html.matchAll(/\sid=["']([^"']+)["']/g)].map(m=>m[1]);
const dup=ids.filter((x,i)=>ids.indexOf(x)!==i);assert.deepEqual([...new Set(dup)],[],`duplicate IDs: ${dup.join(', ')}`);
console.log('PASS: compact iPhone shell, reserved chart viewport, volume, sheets, pen and More actions OK');
