import {BinanceClient} from './binance.js';
import {ChartEngine} from './chart.js';
import {BUILT_INS} from './ta.js';
import {db,KV} from './storage.js';
import {ScriptEngine,DEFAULT_INDICATOR} from './scripts.js';
import {runBacktest} from './backtest.js';
import {ReplayController} from './replay.js';
import {Scanner} from './scanner.js';
import {PaperBroker} from './paper.js';
import {debounce,clamp,formatPrice,formatNumber,formatPct,formatDate,escapeHtml,downloadJSON,parseJSONFile,uid} from './utils.js';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const CHART_TFS=['1m','3m','5m','15m','30m','1h','2h','4h','6h','8h','12h','1d','3d','1w','1M'];
const TF_LABEL=Object.fromEntries(CHART_TFS.map(tf=>[tf,tf.replace('h','H').replace('d','D').replace('w','W')]));
const timeframeOptions=selected=>CHART_TFS.map(tf=>`<option value="${tf}" ${tf===selected?'selected':''}>${TF_LABEL[tf]||tf}</option>`).join('');
const app={
  market:'spot',symbol:'BTCUSDT',timeframe:'1h',layout:1,client:null,scanner:null,scripts:new ScriptEngine(),replay:new ReplayController(),paper:new PaperBroker(),charts:[],activeChart:null,symbols:[],watchlist:['BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','DOGEUSDT'],scriptList:[],selectedScript:null,scannerRows:[],prices:{},tickerMap:new Map(),alerts:[],refreshTimer:null,replaySourceChart:null,
  settings:{theme:'dark',grid:true,volume:true,autoScale:true,syncCrosshair:true,syncSymbol:false,syncTimeframe:false,listingRefresh:300000,language:'ar',panelSizes:{left:260,right:250,bottom:255}},savedCharts:[]
};

async function init(){
  try{
    const saved=await KV.get('workspace',null);if(saved){app.market=saved.market||app.market;app.symbol=saved.symbol||app.symbol;app.timeframe=saved.timeframe||app.timeframe;app.layout=saved.layout||app.layout;app.watchlist=saved.watchlist||app.watchlist;app.settings={...app.settings,...saved.settings};app.savedCharts=saved.charts||[]}
    applyTheme();applyPanelSizes();syncControls();app.client=new BinanceClient(app.market);app.scanner=new Scanner(app.client);wireClient();await app.paper.load();app.alerts=(await db.entries('alerts')).map(([,v])=>v);app.scriptList=await app.scripts.ensureDefaults();renderScripts();renderAlerts();renderPaper();setConnection('loading','Connecting');
    app.symbols=await app.client.loadExchangeInfo();if(!app.client.symbolMap.has(app.symbol)){const first=app.symbols.find(s=>s.quote==='USDT');if(first)app.symbol=first.symbol}renderSymbolResults();renderWatchlist();setLayout(app.layout,true);refreshScanner().catch(logError);scheduleListingRefresh();wireUI();wireReplay();registerSW();await refreshActiveTicker();setConnection('connected','Live');log(`Ready • ${app.market} • ${app.symbol}`)
  }catch(e){setConnection('error','Offline');logError(e);wireUI();toast(`Startup: ${e.message}`,'error')}
}

function wireClient(){
  app.client.on('newSymbols',added=>{const usdt=added.filter(s=>s.quote==='USDT');if(usdt.length){toast(`New Binance listing${usdt.length>1?'s':''}: ${usdt.map(s=>s.symbol).slice(0,4).join(', ')}`,'success');renderSymbolResults();refreshScanner().catch(()=>{})}});app.client.on('error',logError);app.client.on('socket',x=>{if(x.status==='open')setConnection('connected','Live');else if(x.status==='error')setConnection('error','Stream issue')})
}
function setConnection(status,text){const el=$('#connectionStatus');if(!el)return;el.className=`status-dot ${status}`;el.innerHTML=`<i></i>${text}`}
function syncControls(){
  $('#marketSelect').value=app.market;$('#symbolText').textContent=app.symbol;if($('#chartTypeSelect'))$('#chartTypeSelect').value=app.activeChart?.chartType||'candles';if($('#priceScaleModeSelect'))$('#priceScaleModeSelect').value=app.activeChart?.scaleMode||'linear';$('#detailSymbol').textContent=app.symbol;$('#detailMarket').textContent=app.market==='spot'?'Spot':'Futures';$$('#timeframeBar button').forEach(b=>b.classList.toggle('active',b.dataset.tf===app.timeframe));if($('#mobileTimeframeSelect'))$('#mobileTimeframeSelect').value=app.timeframe;syncTf();$('#themeSelect').value=app.settings.theme;$('#gridToggle').checked=app.settings.grid;$('#volumeToggle').checked=app.settings.volume;$('#autoScaleToggle').checked=app.settings.autoScale;$('#syncCrosshairToggle').checked=app.settings.syncCrosshair;$('#syncSymbolToggle').checked=app.settings.syncSymbol;$('#syncTimeframeToggle').checked=app.settings.syncTimeframe;$('#listingRefreshSelect').value=String(app.settings.listingRefresh);$('#languageSelect').value=app.settings.language;$('#defaultMarketSelect').value=app.market
}
function applyTheme(){document.body.classList.toggle('light',app.settings.theme==='light')}
function panelSizes(){
  const d={left:260,right:250,bottom:255};app.settings.panelSizes={...d,...(app.settings.panelSizes||{})};return app.settings.panelSizes;
}
function applyPanelSizes(){
  const p=panelSizes(),root=document.documentElement;if(innerWidth<=760)return;
  root.style.setProperty('--left',`${clamp(+p.left||260,150,520)}px`);
  root.style.setProperty('--right',`${clamp(+p.right||250,170,520)}px`);
  root.style.setProperty('--bottom',`${clamp(+p.bottom||255,37,520)}px`);
  $('#bottomPanel')?.classList.toggle('collapsed',(+p.bottom||255)<=45);
}
function initPanelResizers(){
  const bind=(selector,kind)=>{const el=$(selector);if(!el||el.dataset.wired)return;el.dataset.wired='1';let start=0,initial=0;
    el.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();el.setPointerCapture?.(e.pointerId);start=kind==='bottom'?e.clientY:e.clientX;const p=panelSizes();initial=+p[kind]||({left:260,right:250,bottom:255}[kind]);el.classList.add('dragging');document.body.classList.add('resizing-panels');if(kind==='bottom')document.body.classList.add('resizing-horizontal')});
    el.addEventListener('pointermove',e=>{if(!el.classList.contains('dragging'))return;const delta=(kind==='bottom'?e.clientY:e.clientX)-start;let v=initial;if(kind==='left')v=initial+delta;else if(kind==='right')v=initial-delta;else v=initial-delta;const max=kind==='bottom'?Math.max(120,innerHeight-170):Math.max(220,innerWidth*.42);const min=kind==='bottom'?37:150;panelSizes()[kind]=clamp(v,min,max);applyPanelSizes();app.charts.forEach(c=>c.resize?.());});
    const done=()=>{if(!el.classList.contains('dragging'))return;el.classList.remove('dragging');document.body.classList.remove('resizing-panels','resizing-horizontal');saveWorkspaceDebounced()};el.addEventListener('pointerup',done);el.addEventListener('pointercancel',done);
    el.addEventListener('dblclick',()=>{const u=app.settings.ui||(app.settings.ui={left:true,right:true,bottom:true,rail:true});if(kind==='bottom'){if((+panelSizes().bottom||255)>45){panelSizes().bottom=37;$('#app').classList.add('bottom-min');$('#bottomPanel').classList.add('collapsed')}else{panelSizes().bottom=255;$('#app').classList.remove('bottom-min');$('#bottomPanel').classList.remove('collapsed');u.bottom=true}}else{u[kind]=!u[kind]}applyPanelSizes();applyLayoutUI();saveWorkspaceDebounced()});
  };
  bind('#leftResizer','left');bind('#rightResizer','right');bind('#bottomResizer','bottom');
  window.addEventListener('resize',()=>{applyPanelSizes();app.charts.forEach(c=>c.resize?.())});
}

function renderChartHead(chart){
  if(!chart?.head)return;
  chart.head.innerHTML=`<button class="chart-symbol-local" type="button" title="Select symbol for this chart">${escapeHtml(chart.symbol)}</button><select class="chart-timeframe-local" title="Change timeframe for this chart">${timeframeOptions(chart.timeframe)}</select><span class="chart-type-badge">${chart.chartType==='heikin'?'HA':chart.chartType==='candles'?'Candles':escapeHtml(chart.chartType)}</span>`;
  chart.head.querySelector('.chart-symbol-local')?.addEventListener('click',e=>{e.stopPropagation();setActiveChart(chart);openModal('symbolDialog')});
  chart.head.querySelector('.chart-timeframe-local')?.addEventListener('pointerdown',e=>{e.stopPropagation();setActiveChart(chart)});
  chart.head.querySelector('.chart-timeframe-local')?.addEventListener('change',e=>{e.stopPropagation();changeTimeframe(e.target.value,chart)});
}

function indicatorParamSummary(params={}){return Object.entries(params).slice(0,4).map(([k,v])=>`${k} ${v}`).join(' · ')}
function renderChartIndicatorLegend(chart){
  const el=chart?.legend;if(!el)return;const rows=[];
  for(const i of chart.indicators||[])rows.push({kind:'built',id:i.key,name:i.name,hidden:!!i.hidden,params:indicatorParamSummary(i.params)});
  for(const id of chart.appliedScripts||[])rows.push({kind:'script',id,name:app.scriptList.find(s=>s.id===id)?.name||'Script',hidden:chart.isScriptHidden(id),params:'JS'});
  el.classList.toggle('collapsed',!!chart.legendCollapsed);
  el.innerHTML=`<button class="chart-indicator-legend-toggle" type="button" title="${chart.legendCollapsed?'Show indicators':'Hide indicator list'}">ƒx ${rows.length}${chart.legendCollapsed?' ▾':' ▴'}</button>${rows.map(r=>`<div class="chart-indicator-row ${r.hidden?'hidden-indicator':''}" data-legend-row="${r.id}"><button class="legend-eye" data-legend-eye="${r.id}" data-kind="${r.kind}" title="${r.hidden?'Show':'Hide'}">${r.hidden?'○':'◉'}</button><span class="chart-indicator-name">${escapeHtml(r.name)}</span>${r.params?`<span class="chart-indicator-params">${escapeHtml(r.params)}</span>`:''}<span class="chart-indicator-actions">${r.kind==='built'?`<button data-legend-settings="${r.id}" title="Settings">⚙</button>`:''}<button class="danger" data-legend-remove="${r.id}" data-kind="${r.kind}" title="Remove">×</button></span></div>`).join('')}`;
  el.querySelector('.chart-indicator-legend-toggle')?.addEventListener('click',e=>{e.stopPropagation();chart.legendCollapsed=!chart.legendCollapsed;renderChartIndicatorLegend(chart);saveWorkspaceDebounced()});
  el.querySelectorAll('[data-legend-eye]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();b.dataset.kind==='built'?chart.toggleIndicatorVisibility(b.dataset.legendEye):chart.toggleScriptVisibility(b.dataset.legendEye);renderChartIndicatorLegend(chart);if(chart===app.activeChart){renderActiveIndicators();renderObjectTree()}saveWorkspaceDebounced()}));
  el.querySelectorAll('[data-legend-settings]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();setActiveChart(chart);openIndicatorSettings(b.dataset.legendSettings,chart)}));
  el.querySelectorAll('[data-legend-remove]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();removeChartIndicator(chart,b.dataset.legendRemove,b.dataset.kind)}));
}
function removeChartIndicator(chart,id,kind){
  if(kind==='built')chart.removeIndicator(id);else{chart.appliedScripts=chart.appliedScripts.filter(x=>x!==id);chart.removeScriptSeries(id)}
  renderChartIndicatorLegend(chart);if(chart===app.activeChart){renderActiveIndicators();renderObjectTree()}saveWorkspaceDebounced();
}

async function createChart(config,index){
  const cell=document.createElement('div');cell.className='chart-cell';cell.dataset.index=index;
  cell.innerHTML=`<div class="chart-head"></div><div class="chart-indicator-legend"></div><button class="chart-max" type="button" title="تكبير هذا الشارت">⤢</button><div class="chart-loading">Loading market data…</div>`;
  $('#workspace').appendChild(cell);cell.querySelector('.chart-max').addEventListener('click',e=>{e.stopPropagation();const on=cell.classList.toggle('maximized');e.currentTarget.textContent=on?'⤡':'⤢'});
  const chart=new ChartEngine(cell,{...config,market:app.market});chart.appliedScripts=[...(config.appliedScripts||[])];chart.hiddenScriptIds=new Set(config.hiddenScripts||[]);chart.indicators=[...(config.indicators||[])].map(i=>({...i,hidden:!!i.hidden}));chart.chartType=config.chartType||'candles';chart.scaleMode=config.scaleMode||'linear';chart.legendCollapsed=!!config.legendCollapsed;chart.unsubscribeLive=null;chart.cell=cell;chart.head=cell.querySelector('.chart-head');chart.legend=cell.querySelector('.chart-indicator-legend');chart.loading=cell.querySelector('.chart-loading');chart.grid=app.settings.grid;chart.volume=app.settings.volume;chart.autoScale=app.settings.autoScale;app.charts.push(chart);renderChartHead(chart);renderChartIndicatorLegend(chart);
  cell.addEventListener('pointerdown',()=>setActiveChart(chart),{capture:true});
  chart.on('hover',({bar})=>updateOHLC(bar));
  chart.on('charttype',()=>{renderChartHead(chart);if(chart===app.activeChart)syncControls()});
  chart.on('timeframe',()=>renderChartHead(chart));chart.on('symbol',()=>renderChartHead(chart));chart.on('scaleMode',()=>{if(chart===app.activeChart)syncControls()});
  chart.on('crosshair',c=>{if(chart!==app.activeChart&&c)return;if(app.settings.syncCrosshair)for(const other of app.charts)if(other!==chart)other.setExternalCrosshair(c?.time??null)});
  chart.drawings.onSelection=()=>{if(chart===app.activeChart)renderObjectTree()};
  chart.on('drawings',items=>{saveDrawings(chart,items);if(chart===app.activeChart)renderObjectTree()});
  chart.on('indicators',()=>{renderChartIndicatorLegend(chart);if(chart===app.activeChart){renderActiveIndicators();renderObjectTree()}});
  chart.on('error',logError);chart.on('needHistory',()=>loadOlder(chart));
  chart.drawings.onToolDone=()=>$$('#toolRail [data-tool]').forEach(x=>x.classList.toggle('active',x.dataset.tool==='cursor'));
  chart.on('bar',bar=>{app.prices[chart.symbol]=bar.close;if(chart===app.activeChart){$('#priceStatus').textContent=formatPrice(bar.close);$('#detailPrice').textContent=formatPrice(bar.close)}checkAlerts(chart.symbol,bar.close);app.paper.mark(chart.symbol,bar.close).then(ch=>{if(ch)renderPaper()});rerunScriptsDebounced(chart)});
  if(!app.activeChart)setActiveChart(chart);await loadChart(chart,true);return chart;
}
async function loadChart(chart,fit=true){
  chart.loading.classList.remove('hidden');chart.loading.textContent='Loading market data…';chart.unsubscribeLive?.();chart.unsubscribeLive=null;chart.setSymbol(chart.symbol,app.market);chart.setTimeframe(chart.timeframe);renderChartHead(chart);
  try{const bars=await app.client.klines(chart.symbol,chart.timeframe,1000);chart.setData(bars,{fit});app.prices[chart.symbol]=bars.at(-1)?.close;const drawings=await db.get('drawings',drawingKey(chart),[]);chart.drawings.setItems(drawings);for(const id of chart.appliedScripts||[])await applyScriptToChart(id,chart,false);chart.unsubscribeLive=app.client.subscribeKline(chart.symbol,chart.timeframe,b=>chart.updateBar(b));chart.loading.classList.add('hidden');renderChartIndicatorLegend(chart);if(chart===app.activeChart){updateOHLC(chart.getBarForDisplay(chart.displayLength-1));$('#priceStatus').textContent=formatPrice(bars.at(-1)?.close);refreshActiveTicker().catch(()=>{})}}
  catch(e){chart.loading.textContent=`Market data unavailable: ${e.message}`;logError(e)}
}
function drawingKey(c){return`${app.market}:${c.symbol}:${c.timeframe}`}
const saveDrawings=debounce((chart,items)=>db.set('drawings',drawingKey(chart),items).catch(logError),250);
const rerunScriptsDebounced=debounce(chart=>{for(const id of chart.appliedScripts||[])applyScriptToChart(id,chart,false).catch(()=>{})},550);

function setActiveChart(chart){if(!chart)return;app.activeChart=chart;for(const c of app.charts)c.cell.classList.toggle('active',c===chart);app.symbol=chart.symbol;app.timeframe=chart.timeframe;syncControls();renderActiveIndicators();renderObjectTree();renderChartIndicatorLegend(chart);refreshActiveTicker().catch(()=>{});saveWorkspaceDebounced()}
async function setLayout(n,initial=false){
  n=+n;const configs=app.charts.length?app.charts.map(c=>({symbol:c.symbol,timeframe:c.timeframe,chartType:c.chartType,scaleMode:c.scaleMode,indicators:c.indicators,appliedScripts:c.appliedScripts,hiddenScripts:[...c.hiddenScriptIds],legendCollapsed:!!c.legendCollapsed})):[...(app.savedCharts||[])];for(const c of app.charts){c.unsubscribeLive?.();c.destroy()}app.charts=[];app.activeChart=null;$('#workspace').innerHTML='';$('#workspace').className=`workspace layout-${n}`;app.layout=n;const presets=['5m','15m','1h','4h','1d','1w'];for(let i=0;i<n;i++){const config=configs[i]||{symbol:app.symbol,timeframe:n===1?app.timeframe:presets[i]||app.timeframe};await createChart(config,i)}app.savedCharts=[];closeModal('layoutDialog');if(!initial)saveWorkspaceDebounced()
}
async function changeSymbol(symbol,source=app.activeChart){
  if(!symbol||!app.client.symbolMap.has(symbol))return;if(app.replay.active)app.replay.exit();const target=source||app.activeChart,targets=app.settings.syncSymbol?app.charts:[target];for(const c of targets){c.symbol=symbol;await loadChart(c,true)}setActiveChart(target||targets[0]);closeModal('symbolDialog');saveWorkspaceDebounced()
}
async function changeTimeframe(tf,source=app.activeChart){if(!CHART_TFS.includes(tf)||!source)return;if(app.replay.active)app.replay.exit();const targets=app.settings.syncTimeframe?app.charts:[source];for(const c of targets){c.timeframe=tf;await loadChart(c,true)}setActiveChart(source);saveWorkspaceDebounced()}

function wireUI(){
  $('#chartTypeSelect').addEventListener('change',e=>{if(app.activeChart){app.activeChart.setChartType(e.target.value);renderChartHead(app.activeChart);saveWorkspaceDebounced()}});
  $('#priceScaleModeSelect')?.addEventListener('change',e=>{if(app.activeChart){app.activeChart.setScaleMode(e.target.value);saveWorkspaceDebounced()}});
  $('#marketSelect').addEventListener('change',async e=>{app.market=e.target.value;app.client.closeAll();app.client.setMarket(app.market);app.scanner=new Scanner(app.client);setConnection('loading','Loading market');try{app.symbols=await app.client.loadExchangeInfo(true);if(!app.client.symbolMap.has(app.symbol))app.symbol=app.symbols.find(s=>s.quote==='USDT')?.symbol||app.symbol;renderSymbolResults();renderWatchlist();await setLayout(app.layout);await refreshScanner();setConnection('connected','Live')}catch(err){logError(err);setConnection('error','Offline')}saveWorkspaceDebounced()});
  $('#symbolButton').addEventListener('click',()=>openModal('symbolDialog'));$('#symbolSearch').addEventListener('input',renderSymbolResults);$('#watchlistSearch').addEventListener('input',renderWatchlist);$$('#timeframeBar button').forEach(b=>b.addEventListener('click',()=>changeTimeframe(b.dataset.tf)));$('#mobileTimeframeSelect').addEventListener('change',e=>changeTimeframe(e.target.value));$('#mobileToolsButton').addEventListener('click',()=>$('#toolRail').classList.toggle('mobile-open'));
  $('#layoutButton').addEventListener('click',()=>openModal('layoutDialog'));$$('[data-layout]').forEach(b=>b.addEventListener('click',()=>setLayout(b.dataset.layout)));$('#indicatorButton').addEventListener('click',()=>{renderIndicatorCatalog();openModal('indicatorDialog')});$('#replayButton').addEventListener('click',()=>toggleReplay());$('#saveWorkspaceButton').addEventListener('click',()=>saveWorkspace(true));$('#settingsButton').addEventListener('click',()=>openModal('settingsDialog'));$$('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.closeModal)));$$('.modal-backdrop').forEach(m=>m.addEventListener('pointerdown',e=>{if(e.target===m)closeModal(m.id)}));
  $$('[data-panel-tab]').forEach(b=>b.addEventListener('click',()=>activateTab('[data-panel-tab]','.panel-tab-content',b.dataset.panelTab+'Panel',b)));$$('[data-right-tab]').forEach(b=>b.addEventListener('click',()=>activateTab('[data-right-tab]','.right-tab-content',b.dataset.rightTab==='settings'?'chartSettingsPanel':b.dataset.rightTab+'Panel',b)));$$('[data-bottom-tab]').forEach(b=>b.addEventListener('click',()=>{activateTab('[data-bottom-tab]','.bottom-tab-content',b.dataset.bottomTab+'Bottom',b);if(innerWidth<760)$('#bottomPanel').classList.add('mobile-open')}));$('#bottomPanelToggle').addEventListener('click',()=>{if(innerWidth<760)$('#bottomPanel').classList.toggle('mobile-open');else{$('#bottomPanel').classList.toggle('collapsed');$('#app').classList.toggle('bottom-min')}});
  $$('#toolRail [data-tool]').forEach(b=>b.addEventListener('click',()=>{if(!app.activeChart)return;$$('#toolRail [data-tool]').forEach(x=>x.classList.toggle('active',x===b));app.activeChart.drawings.setTool(b.dataset.tool)}));$('#magnetButton').addEventListener('click',e=>{if(!app.activeChart)return;app.activeChart.drawings.magnet=!app.activeChart.drawings.magnet;e.currentTarget.classList.toggle('active',app.activeChart.drawings.magnet)});$('#undoButton').addEventListener('click',()=>app.activeChart?.drawings.undo());$('#redoButton').addEventListener('click',()=>app.activeChart?.drawings.redo());$('#deleteDrawingButton').addEventListener('click',()=>app.activeChart?.drawings.deleteSelected());
  $('#scannerSort').addEventListener('change',renderScanner);$('#refreshScannerButton').addEventListener('click',()=>refreshScanner());
  $('#themeSelect').addEventListener('change',e=>{app.settings.theme=e.target.value;applyTheme();app.charts.forEach(c=>c.requestDraw());saveWorkspaceDebounced()});$('#gridToggle').addEventListener('change',e=>updateChartSetting('grid',e.target.checked));$('#volumeToggle').addEventListener('change',e=>updateChartSetting('volume',e.target.checked));$('#autoScaleToggle').addEventListener('change',e=>updateChartSetting('autoScale',e.target.checked));$('#syncCrosshairToggle').addEventListener('change',e=>{app.settings.syncCrosshair=e.target.checked;saveWorkspaceDebounced()});$('#syncSymbolToggle').addEventListener('change',e=>{app.settings.syncSymbol=e.target.checked;saveWorkspaceDebounced()});$('#syncTimeframeToggle').addEventListener('change',e=>{app.settings.syncTimeframe=e.target.checked;saveWorkspaceDebounced()});$('#listingRefreshSelect').addEventListener('change',e=>{app.settings.listingRefresh=+e.target.value;scheduleListingRefresh();saveWorkspaceDebounced()});
  $('#newScriptButton').addEventListener('click',newScript);$('#saveScriptButton').addEventListener('click',saveCurrentScript);$('#runScriptButton').addEventListener('click',runSelectedScript);$('#addScriptToChartButton').addEventListener('click',runSelectedScript);$('#favoriteScriptButton').addEventListener('click',toggleFavoriteScript);$('#runBacktestButton').addEventListener('click',runSelectedBacktest);
  $('#indicatorSettingsForm').addEventListener('submit',applyIndicatorSettings);$('#resetIndicatorSettingsButton')?.addEventListener('click',resetIndicatorSettings);$('#alertForm').addEventListener('submit',createAlert);$('#paperOrderForm').addEventListener('submit',placePaperOrder);$$('[data-side]').forEach(b=>b.addEventListener('click',()=>{$$('[data-side]').forEach(x=>x.classList.toggle('active',x===b))}));
  $('#exportButton').addEventListener('click',async()=>downloadJSON(`binance-studio-${new Date().toISOString().slice(0,10)}.json`,await db.exportAll()));$('#importButton').addEventListener('click',()=>$('#importFile').click());$('#importFile').addEventListener('change',async e=>{if(!e.target.files[0])return;try{const data=await parseJSONFile(e.target.files[0]);await db.importAll(data);toast('Import complete. Reloading…','success');setTimeout(()=>location.reload(),600)}catch(err){toast(err.message,'error')}});
  $('#languageSelect').addEventListener('change',e=>{app.settings.language=e.target.value;saveWorkspaceDebounced()});
  document.addEventListener('keydown',keyboardShortcuts);wireEnhancements()
}
function activateTab(buttonSelector,contentSelector,id,button){$$(buttonSelector).forEach(x=>x.classList.toggle('active',x===button));$$(contentSelector).forEach(x=>x.classList.toggle('active',x.id===id))}
function updateChartSetting(k,v){app.settings[k]=v;for(const c of app.charts){c[k]=v;if(k==='autoScale'&&v){c.priceZoom=1;c.frozen=null}c.requestDraw()}saveWorkspaceDebounced()}
function openModal(id){$('#'+id)?.classList.remove('hidden');if(id==='symbolDialog')setTimeout(()=>$('#symbolSearch').focus(),20)}function closeModal(id){$('#'+id)?.classList.add('hidden')}

function renderSymbolResults(){const el=$('#symbolResults');if(!el)return;const q=($('#symbolSearch')?.value||'').trim().toUpperCase();const syms=app.symbols.filter(s=>(!q||s.symbol.includes(q)||s.base.includes(q))&&(q?s.quote==='USDT'||s.symbol.includes(q):s.quote==='USDT')).slice(0,180);el.innerHTML=syms.map(s=>`<div class="symbol-result" data-symbol="${s.symbol}"><button class="watch-star" data-watch-star="${s.symbol}" title="Watchlist">${app.watchlist.includes(s.symbol)?'★':'☆'}</button><strong>${s.base}</strong><span class="muted">/${s.quote}</span><span class="push muted">${app.market==='spot'?'Spot':'Perp'}</span></div>`).join('');el.querySelectorAll('[data-symbol]').forEach(x=>x.addEventListener('click',()=>changeSymbol(x.dataset.symbol)));el.querySelectorAll('[data-watch-star]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();toggleWatchlist(b.dataset.watchStar);renderSymbolResults()}))}
function renderWatchlist(){const el=$('#watchlistList');if(!el)return;const q=($('#watchlistSearch')?.value||'').trim().toUpperCase();const list=app.watchlist.filter(s=>(!q||s.includes(q))&&app.client?.symbolMap.has(s));el.innerHTML=list.map(s=>{const t=app.tickerMap.get(s);return`<div class="symbol-row" data-symbol="${s}"><div class="symbol-main"><button class="watch-star star" data-remove-watch="${s}" title="Remove">★</button><div><strong>${s.replace('USDT','')}</strong><div class="symbol-meta">${s.endsWith('USDT')?'USDT':''}</div></div></div><span>${formatPrice(t?.price)}</span><span class="${(t?.change||0)>=0?'price-up':'price-down'}">${t?formatPct(t.change):'—'}</span></div>`}).join('');el.querySelectorAll('[data-symbol]').forEach(x=>x.addEventListener('click',()=>changeSymbol(x.dataset.symbol)));el.querySelectorAll('[data-remove-watch]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();toggleWatchlist(b.dataset.removeWatch)}))}
function toggleWatchlist(symbol){const i=app.watchlist.indexOf(symbol);if(i>=0)app.watchlist.splice(i,1);else app.watchlist.unshift(symbol);renderWatchlist();saveWorkspaceDebounced()}
async function refreshScanner(){if(!app.scanner)return;try{app.scannerRows=await app.scanner.refresh('USDT');app.tickerMap=new Map(app.scannerRows.map(x=>[x.symbol,x]));renderScanner();renderWatchlist();await refreshActiveTicker();return app.scannerRows}catch(e){logError(e);throw e}}
function renderScanner(){const el=$('#scannerList');if(!el||!app.scanner)return;const sort=$('#scannerSort').value,rows=app.scanner.sorted(sort,true).slice(0,150);el.innerHTML=rows.map(r=>`<div class="scanner-row" data-symbol="${r.symbol}"><div><strong>${r.symbol.replace('USDT','')}</strong><small class="muted">${formatNumber(r.volume)} USDT</small></div><div class="scanner-values"><span>${formatPrice(r.price)}</span><small class="${r.change>=0?'price-up':'price-down'}">${formatPct(r.change)}</small></div></div>`).join('');el.querySelectorAll('[data-symbol]').forEach(x=>x.addEventListener('click',()=>changeSymbol(x.dataset.symbol)))}
async function refreshActiveTicker(){const s=app.activeChart?.symbol||app.symbol;let t=app.tickerMap.get(s);if(!t){try{const r=await app.client.ticker24h(s);t={symbol:s,price:+r.lastPrice,change:+r.priceChangePercent,volume:+r.quoteVolume,high:+r.highPrice,low:+r.lowPrice};app.tickerMap.set(s,t)}catch{return}}$('#detailSymbol').textContent=s;$('#detailPrice').textContent=formatPrice(t.price);$('#detailChange').textContent=formatPct(t.change);$('#detailChange').className=t.change>=0?'price-up':'price-down';$('#detailHigh').textContent=formatPrice(t.high);$('#detailLow').textContent=formatPrice(t.low);$('#detailVolume').textContent=formatNumber(t.volume);$('#detailMarket').textContent=app.market==='spot'?'Spot':'Futures'}
function updateOHLC(b){if(!b)return;$('#ohlcStatus').textContent=`O ${formatPrice(b.open)}  H ${formatPrice(b.high)}  L ${formatPrice(b.low)}  C ${formatPrice(b.close)}  V ${formatNumber(b.volume)}`;$('#priceStatus').textContent=formatPrice(b.close)}

function renderIndicatorCatalog(){const el=$('#indicatorCatalog'),q=($('#indicatorSearch')?.value||'').toLowerCase();const built=Object.values(BUILT_INS).filter(x=>x.name.toLowerCase().includes(q)||x.id.includes(q)||(x.category||'').toLowerCase().includes(q)).sort((a,b)=>(b.category==='BCS Pro Suite')-(a.category==='BCS Pro Suite'));const custom=app.scriptList.filter(s=>s.type==='indicator'&&(!q||s.name.toLowerCase().includes(q)));el.innerHTML=`${built.map(x=>`<div class="indicator-item" data-built="${x.id}"><div><strong>${x.category==='BCS Pro Suite'?'<span class="pro-badge">BCS PRO</span> ':''}${x.name}</strong><p>${x.category?`${x.category} • `:''}${x.overlay?'Overlay on price':'Separate pane'}</p></div><span class="push">＋</span></div>`).join('')}${custom.map(s=>`<div class="indicator-item" data-script="${s.id}"><div><strong>${s.favorite?'★ ':''}${escapeHtml(s.name)}</strong><p>My JavaScript Script</p></div><span class="push">＋</span></div>`).join('')}`;el.querySelectorAll('[data-built]').forEach(x=>x.addEventListener('click',()=>{app.activeChart?.addIndicator(x.dataset.built);renderActiveIndicators();closeModal('indicatorDialog')}));el.querySelectorAll('[data-script]').forEach(x=>x.addEventListener('click',async()=>{await applyScriptToChart(x.dataset.script,app.activeChart,true);closeModal('indicatorDialog')}))}
$('#indicatorSearch')?.addEventListener('input',renderIndicatorCatalog);
function renderActiveIndicators(){
  const el=$('#activeIndicatorList');if(!el||!app.activeChart)return;const a=app.activeChart;
  const built=a.indicators.map(i=>({key:i.key,name:i.name,type:'built',hidden:!!i.hidden,params:indicatorParamSummary(i.params)}));
  const custom=(a.appliedScripts||[]).map(id=>({key:id,name:app.scriptList.find(s=>s.id===id)?.name||'Script',type:'script',hidden:a.isScriptHidden(id),params:'JS'}));
  el.innerHTML=[...built,...custom].map(i=>`<span class="chip ${i.hidden?'muted':''}"><button data-ind-eye="${i.key}" data-kind="${i.type}" title="${i.hidden?'Show':'Hide'}">${i.hidden?'○':'◉'}</button><span>${escapeHtml(i.name)}${i.params?` <small>${escapeHtml(i.params)}</small>`:''}</span>${i.type==='built'?`<button data-ind-settings="${i.key}" title="Settings">⚙</button>`:''}<button data-remove="${i.key}" data-kind="${i.type}" title="Remove">×</button></span>`).join('');
  el.querySelectorAll('[data-ind-eye]').forEach(b=>b.addEventListener('click',()=>{b.dataset.kind==='built'?a.toggleIndicatorVisibility(b.dataset.indEye):a.toggleScriptVisibility(b.dataset.indEye);renderActiveIndicators();renderChartIndicatorLegend(a);renderObjectTree();saveWorkspaceDebounced()}));
  el.querySelectorAll('[data-ind-settings]').forEach(b=>b.addEventListener('click',()=>openIndicatorSettings(b.dataset.indSettings,a)));
  el.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>removeChartIndicator(a,b.dataset.remove,b.dataset.kind)));
}
let editingIndicatorKey=null,editingIndicatorChartId=null;
function openIndicatorSettings(key,chart=app.activeChart){
  const item=chart?.indicators.find(x=>x.key===key);if(!item)return;editingIndicatorKey=key;editingIndicatorChartId=chart.id;$('#indicatorSettingsTitle').textContent=item.name;
  const fields=$('#indicatorSettingsFields');fields.innerHTML=Object.entries(item.params||{}).map(([k,v])=>`<label>${escapeHtml(k)}<input name="${escapeHtml(k)}" type="number" step="any" value="${Number(v)}"></label>`).join('')||'<div class="muted">No numeric inputs for this indicator</div>';openModal('indicatorSettingsDialog');
}
function editingIndicator(){const chart=app.charts.find(c=>c.id===editingIndicatorChartId)||app.activeChart;return{chart,item:chart?.indicators.find(x=>x.key===editingIndicatorKey)}}
function resetIndicatorSettings(){
  const {chart,item}=editingIndicator();if(!chart||!item)return;const def=Object.values(BUILT_INS).find(x=>x.id===item.id);if(!def)return;item.params={...def.defaults};chart.recomputeIndicators();openIndicatorSettings(item.key,chart);renderActiveIndicators();renderChartIndicatorLegend(chart);renderObjectTree();saveWorkspaceDebounced();
}
function applyIndicatorSettings(e){
  e.preventDefault();const {chart,item}=editingIndicator();if(!chart||!item)return;const fd=new FormData(e.currentTarget);for(const k of Object.keys(item.params||{})){const v=+fd.get(k);if(Number.isFinite(v))item.params[k]=v}chart.recomputeIndicators();renderChartIndicatorLegend(chart);if(chart===app.activeChart){renderActiveIndicators();renderObjectTree()}closeModal('indicatorSettingsDialog');saveWorkspaceDebounced();
}
function renderObjectTree(){
  const el=$('#objectTree');if(!el||!app.activeChart)return;const c=app.activeChart,rows=[];
  for(const i of c.indicators)rows.push({kind:'indicator',id:i.key,name:i.name,hidden:!!i.hidden,locked:false});
  for(const id of c.appliedScripts||[])rows.push({kind:'script',id,name:app.scriptList.find(s=>s.id===id)?.name||'Script',hidden:c.isScriptHidden(id),locked:false});
  for(const d of c.drawings.items)rows.push({kind:'drawing',id:d.id,name:d.type,hidden:!!d.hidden,locked:!!d.locked,selected:c.drawings.selected===d.id});
  el.innerHTML=rows.length?rows.map(r=>`<div class="object-item ${r.selected?'selected':''}" data-object-row="${r.id}" data-kind="${r.kind}"><span>${r.kind==='drawing'?'✎':'ƒx'}</span><span>${escapeHtml(r.name)}</span><span class="muted">${r.kind}</span><span class="object-actions"><button data-object-eye="${r.id}" data-kind="${r.kind}" title="${r.hidden?'Show':'Hide'}">${r.hidden?'○':'◉'}</button>${r.kind==='indicator'?`<button data-object-settings="${r.id}" title="Settings">⚙</button>`:''}${r.kind==='drawing'?`<button data-object-lock="${r.id}" title="${r.locked?'Unlock':'Lock'}">${r.locked?'🔒':'🔓'}</button>`:''}<button class="danger" data-object-delete="${r.id}" data-kind="${r.kind}" title="Delete">×</button></span></div>`).join(''):'<div class="muted" style="padding:8px">No objects</div>';
  el.querySelectorAll('[data-object-row]').forEach(row=>row.addEventListener('click',e=>{if(e.target.closest('button'))return;if(row.dataset.kind==='drawing'){c.drawings.select(row.dataset.objectRow);renderObjectTree()}}));
  el.querySelectorAll('[data-object-eye]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.kind==='drawing')c.drawings.toggleVisibility(b.dataset.objectEye);else if(b.dataset.kind==='indicator')c.toggleIndicatorVisibility(b.dataset.objectEye);else c.toggleScriptVisibility(b.dataset.objectEye);renderObjectTree();renderActiveIndicators();renderChartIndicatorLegend(c);saveWorkspaceDebounced()}));
  el.querySelectorAll('[data-object-settings]').forEach(b=>b.addEventListener('click',()=>openIndicatorSettings(b.dataset.objectSettings,c)));
  el.querySelectorAll('[data-object-lock]').forEach(b=>b.addEventListener('click',()=>{c.drawings.toggleLock(b.dataset.objectLock);renderObjectTree()}));
  el.querySelectorAll('[data-object-delete]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.kind==='drawing')c.drawings.delete(b.dataset.objectDelete);else removeChartIndicator(c,b.dataset.objectDelete,b.dataset.kind==='indicator'?'built':'script');renderObjectTree()}));
}

function renderScripts(){const el=$('#scriptList');if(!el)return;el.innerHTML=app.scriptList.map(s=>`<div class="script-item ${app.selectedScript?.id===s.id?'active':''}" data-script-id="${s.id}"><strong>${s.favorite?'★ ':''}${escapeHtml(s.name)}</strong><small>${s.type} • ${new Date(s.updatedAt).toLocaleDateString()}</small></div>`).join('');el.querySelectorAll('[data-script-id]').forEach(x=>x.addEventListener('click',()=>selectScript(x.dataset.scriptId)));if(!app.selectedScript&&app.scriptList.length)selectScript(app.scriptList[0].id)}
function selectScript(id){app.selectedScript=app.scriptList.find(s=>s.id===id)||null;if(!app.selectedScript)return;$('#scriptName').value=app.selectedScript.name;$('#scriptType').value=app.selectedScript.type;$('#scriptEditor').value=app.selectedScript.source;$('#favoriteScriptButton').textContent=app.selectedScript.favorite?'★':'☆';renderScripts()}
function newScript(){app.selectedScript={id:null,name:'New Indicator',type:'indicator',source:DEFAULT_INDICATOR,favorite:false};$('#scriptName').value=app.selectedScript.name;$('#scriptType').value='indicator';$('#scriptEditor').value=app.selectedScript.source;$('#favoriteScriptButton').textContent='☆'}
async function saveCurrentScript(){try{const s=await app.scripts.save({...app.selectedScript,name:$('#scriptName').value.trim()||'Untitled',type:$('#scriptType').value,source:$('#scriptEditor').value});app.selectedScript=s;app.scriptList=await app.scripts.list();renderScripts();renderIndicatorCatalog();toast('Script saved','success')}catch(e){showScriptError(e)}}
async function toggleFavoriteScript(){if(!app.selectedScript)return;app.selectedScript.favorite=!app.selectedScript.favorite;await saveCurrentScript()}
async function runSelectedScript(){if(!app.selectedScript||!app.activeChart)return;await saveCurrentScript();try{const r=await app.scripts.run(app.selectedScript,app.activeChart.bars);if(r.type==='indicator'){app.activeChart.setScriptSeries(app.selectedScript.id,r.name,r.plots,r.overlay);if(!app.activeChart.appliedScripts.includes(app.selectedScript.id))app.activeChart.appliedScripts.push(app.selectedScript.id);$('#scriptConsole').textContent=`✓ ${r.name}: ${r.plots.length} plot(s), ${app.activeChart.bars.length} bars`;renderActiveIndicators();renderObjectTree();toast(`${r.name} added to chart`,'success')}else{$('#scriptConsole').textContent=`✓ ${r.name}: ${r.orders.length} strategy order(s)`;toast('Strategy compiled. Open Strategy Tester.','success')}}catch(e){showScriptError(e)}}
async function applyScriptToChart(id,chart,persist=true){const s=app.scriptList.find(x=>x.id===id);if(!s||s.type!=='indicator'||!chart?.bars.length)return;try{const r=await app.scripts.run(s,chart.bars);chart.setScriptSeries(s.id,r.name,r.plots,r.overlay);if(persist&&!chart.appliedScripts.includes(id))chart.appliedScripts.push(id);if(chart===app.activeChart)renderActiveIndicators()}catch(e){if(persist)showScriptError(e)}}
function showScriptError(e){$('#scriptConsole').textContent=`✕ ${e.message}`;toast(e.message,'error');logError(e)}

async function runSelectedBacktest(){let s=app.selectedScript;if(!s||s.type!=='strategy')s=app.scriptList.find(x=>x.type==='strategy');if(!s||!app.activeChart)return toast('Create or select a strategy script first','error');try{const out=await app.scripts.run(s,app.activeChart.bars);const result=runBacktest(app.activeChart.bars,out.orders,{capital:+$('#btCapital').value,feePct:+$('#btFee').value,slippagePct:+$('#btSlippage').value,positionPct:+$('#btPositionSize').value});const markers=[];for(const t of result.trades){markers.push({index:t.entryIndex,side:t.side,label:t.side==='long'?'L':'S'});markers.push({index:t.exitIndex,side:t.side==='long'?'sell':'buy',label:'X'})}app.activeChart.setMarkers(markers);renderBacktest(result);$('#scriptConsole').textContent=`Backtest ${s.name}: ${result.totalTrades} trades`;toast('Backtest complete','success')}catch(e){showScriptError(e)}}
function renderBacktest(r){const metrics=[['Net profit',`${r.netProfit>=0?'+':''}${formatNumber(r.netProfit)} (${r.netProfitPct.toFixed(2)}%)`],['Trades',r.totalTrades],['Win rate',`${r.winRate.toFixed(2)}%`],['Profit factor',Number.isFinite(r.profitFactor)?r.profitFactor.toFixed(2):'∞'],['Max drawdown',`${r.maxDrawdownPct.toFixed(2)}%`],['Final equity',formatNumber(r.finalEquity)]];$('#backtestStats').innerHTML=metrics.map(([a,b])=>`<div class="metric"><span>${a}</span><strong>${b}</strong></div>`).join('');$('#tradeTable').innerHTML=`<table><thead><tr><th>#</th><th>Side</th><th>Entry</th><th>Exit</th><th>PnL</th><th>Return</th><th>Reason</th></tr></thead><tbody>${r.trades.map((t,i)=>`<tr><td>${i+1}</td><td>${t.side}</td><td>${formatPrice(t.entryPrice)}</td><td>${formatPrice(t.exitPrice)}</td><td class="${t.pnl>=0?'price-up':'price-down'}">${formatNumber(t.pnl)}</td><td>${t.returnPct.toFixed(2)}%</td><td>${t.reason}</td></tr>`).join('')}</tbody></table>`;drawEquity(r.curve)}
function drawEquity(curve){const c=$('#equityCanvas'),r=c.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1);c.width=r.width*dpr;c.height=r.height*dpr;const x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,r.width,r.height);if(!curve.length)return;const vals=curve.map(p=>p.equity),min=Math.min(...vals),max=Math.max(...vals),pad=10;x.strokeStyle='#2962ff';x.lineWidth=1.5;x.beginPath();curve.forEach((p,i)=>{const px=pad+i/(curve.length-1||1)*(r.width-pad*2),py=r.height-pad-(p.equity-min)/(max-min||1)*(r.height-pad*2);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();x.fillStyle='#8190a3';x.font='10px system-ui';x.fillText(`Equity ${formatNumber(vals.at(-1))}`,8,13)}

function wireReplay(){
  app.replay.on('change',st=>{
    if(!st.active)return;const base=app.replaySourceChart;if(!base?.bars.length)return;
    const sourceIndex=clamp(st.index,0,base.bars.length-1),t=base.bars[sourceIndex]?.time;if(!t)return;
    for(const c of app.charts){const idx=c===base?sourceIndex:c.findTimeIndexAtOrBefore(t,true);c.setReplayIndex(idx)}
    $('#replayPlayButton').textContent=st.playing?'Ⅱ':'▶';$('#replayTime').textContent=formatDate(t);
  });
  app.replay.on('exit',()=>{for(const c of app.charts)c.clearReplay();app.replaySourceChart=null;$('#replayBar').classList.add('hidden');updateOHLC(app.activeChart?.getBarForDisplay(app.activeChart.displayLength-1))});
  $('#replayStartHereButton').addEventListener('click',()=>startReplay());$('#replayPlayButton').addEventListener('click',()=>app.replay.play());$('#replayStepButton').addEventListener('click',()=>app.replay.step());$('#replayBackButton').addEventListener('click',()=>app.replay.back());$('#replayExitButton').addEventListener('click',()=>app.replay.exit());$('#replaySpeed').addEventListener('change',e=>app.replay.setSpeed(e.target.value));
}
function toggleReplay(){if(app.replay.active)app.replay.exit();else{$('#replayBar').classList.remove('hidden');startReplay()}}
function startReplay(){
  const c=app.activeChart;if(!c?.bars?.length||c.bars.length<3)return;app.replaySourceChart=c;
  const requested=c.crosshair?.index??Math.floor(c.bars.length*.65),idx=clamp(Math.floor(requested),1,c.bars.length-2);$('#replayBar').classList.remove('hidden');app.replay.start(c.bars.length,idx);
}

async function createAlert(e){e.preventDefault();const price=+$('#alertPrice').value;if(!price||!app.activeChart)return;const a={id:uid('alert'),symbol:app.activeChart.symbol,market:app.market,condition:$('#alertCondition').value,price,message:$('#alertMessage').value||`${app.activeChart.symbol} ${$('#alertCondition').value} ${price}`,active:true,createdAt:Date.now(),lastTriggered:null};app.alerts.push(a);await db.set('alerts',a.id,a);if('Notification'in window&&Notification.permission==='default')Notification.requestPermission();renderAlerts();e.target.reset();toast('Alert created','success')}
function checkAlerts(symbol,price){for(const a of app.alerts){if(!a.active||a.symbol!==symbol||a.market!==app.market)continue;const hit=a.condition==='above'?price>=a.price:price<=a.price;if(hit&&!a.lastTriggered){a.lastTriggered=Date.now();a.active=false;db.set('alerts',a.id,a);toast(a.message,'success');if('Notification'in window&&Notification.permission==='granted')new Notification('Binance Studio Alert',{body:a.message});renderAlerts()}}}
function renderAlerts(){const el=$('#alertList');if(!el)return;el.innerHTML=app.alerts.slice().reverse().map(a=>`<div class="alert-item"><strong>${a.symbol} ${a.condition} ${formatPrice(a.price)}</strong><small>${escapeHtml(a.message)} • ${a.active?'Active':'Triggered'}</small><button data-alert-delete="${a.id}" style="float:right;border:0;background:transparent;color:var(--muted)">×</button></div>`).join('');el.querySelectorAll('[data-alert-delete]').forEach(b=>b.addEventListener('click',async()=>{app.alerts=app.alerts.filter(a=>a.id!==b.dataset.alertDelete);await db.del('alerts',b.dataset.alertDelete);renderAlerts()}))}

async function placePaperOrder(e){e.preventDefault();const c=app.activeChart,price=app.prices[c?.symbol]||c?.bars.at(-1)?.close;if(!c||!price)return;const side=$$('[data-side]').find(x=>x.classList.contains('active'))?.dataset.side||'long';try{await app.paper.order({symbol:c.symbol,side,qty:+$('#paperQty').value,price,stop:+$('#paperStop').value||null,take:+$('#paperTake').value||null});renderPaper();toast(`Paper ${side} opened`,'success')}catch(err){toast(err.message,'error')}}
function renderPaper(){const s=app.paper.summary(app.prices);$('#paperSummary').innerHTML=[['Balance',formatNumber(s.balance)],['Equity',formatNumber(s.equity)],['Unrealized',formatNumber(s.unrealized)],['Realized',formatNumber(s.realized)],['Positions',s.count]].map(([a,b])=>`<div class="metric"><span>${a}</span><strong>${b}</strong></div>`).join('');$('#paperPositions').innerHTML=`<table><thead><tr><th>Symbol</th><th>Side</th><th>Qty</th><th>Entry</th><th>Mark</th><th>PnL</th><th></th></tr></thead><tbody>${app.paper.state.positions.map(p=>{const mark=app.prices[p.symbol]||p.entry,pnl=(mark-p.entry)*p.qty*(p.side==='long'?1:-1);return`<tr><td>${p.symbol}</td><td>${p.side}</td><td>${p.qty}</td><td>${formatPrice(p.entry)}</td><td>${formatPrice(mark)}</td><td class="${pnl>=0?'price-up':'price-down'}">${formatNumber(pnl)}</td><td><button data-close-pos="${p.id}">Close</button></td></tr>`}).join('')}</tbody></table>`;$('#paperPositions').querySelectorAll('[data-close-pos]').forEach(b=>b.addEventListener('click',async()=>{const p=app.paper.state.positions.find(x=>x.id===b.dataset.closePos),price=app.prices[p.symbol]||p.entry;await app.paper.close(p.id,price);renderPaper()}))}

function renderObjectMaybe(){renderObjectTree()}
function updateOHLCMaybe(){updateOHLC(app.activeChart?.bars.at(-1))}
async function saveWorkspace(notify=false){const data={market:app.market,symbol:app.symbol,timeframe:app.timeframe,layout:app.layout,watchlist:app.watchlist,settings:app.settings,charts:app.charts.map(c=>({symbol:c.symbol,timeframe:c.timeframe,chartType:c.chartType,scaleMode:c.scaleMode,indicators:c.indicators,appliedScripts:c.appliedScripts,hiddenScripts:[...c.hiddenScriptIds],legendCollapsed:!!c.legendCollapsed}))};await KV.set('workspace',data);if(notify)toast('Workspace saved','success')}
const saveWorkspaceDebounced=debounce(()=>saveWorkspace(false).catch(logError),350);
function scheduleListingRefresh(){clearInterval(app.refreshTimer);app.refreshTimer=setInterval(async()=>{try{app.symbols=await app.client.loadExchangeInfo(true);renderSymbolResults()}catch(e){logError(e)}},app.settings.listingRefresh);clearInterval(app.scannerTimer);app.scannerTimer=setInterval(()=>refreshScanner().catch(()=>{}),45000)}

function keyboardShortcuts(e){const typing=['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName);if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();if(e.target=== $('#scriptEditor'))saveCurrentScript();else saveWorkspace(true);return}if(e.key==='Escape'){const openM=$$('.modal-backdrop:not(.hidden)');if(openM.length){openM.forEach(m=>closeModal(m.id));return}$('#tfMenu')?.classList.add('hidden');if($('#app').classList.contains('focus')){toggleFocus();return}app.activeChart?.drawings.cancel();return}if(typing)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();app.activeChart?.drawings.undo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();app.activeChart?.drawings.redo();return}if(e.key==='Delete'||e.key==='Backspace'){app.activeChart?.drawings.deleteSelected();return}if(e.key==='/'){e.preventDefault();openModal('symbolDialog');return}
  const ch=app.activeChart;if(e.altKey){const pk={Digit1:'rail',Digit2:'left',Digit3:'bottom',Digit4:'right'}[e.code];if(pk){e.preventDefault();togglePanel(pk);return}}if(ch&&!e.ctrlKey&&!e.metaKey&&!e.altKey){if(e.key==='+'||e.key==='='){ch.zoomBy(1.2);return}if(e.key==='-'||e.key==='_'){ch.zoomBy(1/1.2);return}if(e.key==='ArrowLeft'){ch.panBy(e.shiftKey?-25:-5);return}if(e.key==='ArrowRight'){ch.panBy(e.shiftKey?25:5);return}if(e.key==='End'){ch.scrollToLatest();return}if(e.key==='Home'){ch.fitContent();return}if(e.key==='F'&&e.shiftKey){toggleFocus();return}}if(e.code==='Space'&&app.replay.active){e.preventDefault();app.replay.play();return}const map={t:'trend',f:'fib',h:'horizontal',v:'vertical',r:'rectangle',m:'measure'};const tool=map[e.key.toLowerCase()];if(tool){const b=$(`#toolRail [data-tool="${tool}"]`);b?.click()}}

function toast(msg,type=''){const host=$('#toastHost'),el=document.createElement('div');el.className=`toast ${type}`;el.textContent=msg;host.appendChild(el);setTimeout(()=>el.remove(),3600)}
function log(msg){const line=`[${new Date().toLocaleTimeString()}] ${msg}`;console.log(line);const el=$('#appLog');if(el){el.textContent+=line+'\n';el.scrollTop=el.scrollHeight}}
function logError(e){console.error(e);log(`ERROR: ${e?.message||e}`)}
function registerSW(){if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(r=>r.update()).catch(logError)}

const TFS=CHART_TFS;
const tfLabel=t=>TF_LABEL[t]||t;
function syncTf(){const inBar=!!$(`#timeframeBar [data-tf="${app.timeframe}"]`),b=$('#tfMoreButton');if(b){b.textContent=inBar?'▾':`${tfLabel(app.timeframe)} ▾`;b.classList.toggle('active',!inBar)}$$('#tfMenu button').forEach(x=>x.classList.toggle('active',x.dataset.tf===app.timeframe))}
function applyLayoutUI(){const u=app.settings.ui||(app.settings.ui={left:true,right:true,bottom:true,rail:true}),a=$('#app'),focus=a.classList.contains('focus');a.classList.toggle('hide-left',!u.left);a.classList.toggle('hide-right',!u.right);a.classList.toggle('hide-bottom',!u.bottom);a.classList.toggle('hide-rail',!u.rail);[['rail','#toggleRail'],['left','#toggleLeft'],['bottom','#toggleBottom'],['right','#toggleRight']].forEach(([k,s])=>$(s)?.classList.toggle('active',!!u[k]&&!(focus&&k!=='rail')));$('#focusButton')?.classList.toggle('active',focus);[['left','#edgeLeft'],['right','#edgeRight'],['bottom','#edgeBottom']].forEach(([k,s])=>$(s)?.classList.toggle('hidden',!!u[k]&&!focus))}
function togglePanel(k){const a=$('#app'),u=app.settings.ui;if(a.classList.contains('focus')){a.classList.remove('focus');u[k]=true}else u[k]=!u[k];if(k==='bottom'&&u.bottom){a.classList.remove('bottom-min');$('#bottomPanel').classList.remove('collapsed')}applyLayoutUI();saveWorkspaceDebounced()}
function toggleFocus(){$('#app').classList.toggle('focus');applyLayoutUI()}
async function loadOlder(chart){if(chart.loadingHistory||chart.noMoreHistory||!chart.bars.length)return;chart.loadingHistory=true;const key=`${chart.symbol}:${chart.timeframe}`;try{const first=chart.bars[0].time,older=await app.client.klines(chart.symbol,chart.timeframe,1000,first-1);if(key!==`${chart.symbol}:${chart.timeframe}`)return;const fresh=older.filter(b=>b.time<first);if(fresh.length<2)chart.noMoreHistory=true;if(fresh.length){chart.prependBars(fresh);for(const id of chart.appliedScripts||[])applyScriptToChart(id,chart,false).catch(()=>{})}}catch(e){logError(e)}finally{chart.loadingHistory=false}}
function wireEnhancements(){
  applyLayoutUI();applyPanelSizes();initPanelResizers();const menu=$('#tfMenu');menu.innerHTML=TFS.map(t=>`<button data-tf="${t}">${tfLabel(t)}</button>`).join('');
  menu.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{menu.classList.add('hidden');changeTimeframe(b.dataset.tf)}));
  $('#tfMoreButton').addEventListener('click',e=>{e.stopPropagation();const r=e.currentTarget.getBoundingClientRect();menu.classList.toggle('hidden');menu.style.top=`${r.bottom+4}px`;menu.style.left=`${Math.max(4,Math.min(r.left,innerWidth-menu.offsetWidth-6))}px`});
  document.addEventListener('pointerdown',e=>{if(!menu.contains(e.target)&&e.target.id!=='tfMoreButton')menu.classList.add('hidden')});
  $('#mobileTimeframeSelect').innerHTML=TFS.map(t=>`<option value="${t}">${tfLabel(t)}</option>`).join('');$('#mobileTimeframeSelect').value=app.timeframe;syncTf();
  [['#toggleRail','rail'],['#toggleLeft','left'],['#toggleBottom','bottom'],['#toggleRight','right']].forEach(([s,k])=>$(s).addEventListener('click',()=>togglePanel(k)));
  [['#edgeLeft','left'],['#edgeRight','right'],['#edgeBottom','bottom']].forEach(([s,k])=>$(s).addEventListener('click',()=>{$('#app').classList.remove('focus');app.settings.ui[k]=true;if(k==='bottom'){$('#app').classList.remove('bottom-min');$('#bottomPanel').classList.remove('collapsed')}applyLayoutUI();saveWorkspaceDebounced()}));
  $('#focusButton').addEventListener('click',toggleFocus);
  const C=()=>app.activeChart;$('#zoomInButton').addEventListener('click',()=>C()?.zoomBy(1.25));$('#zoomOutButton').addEventListener('click',()=>C()?.zoomBy(.8));$('#fitButton').addEventListener('click',()=>{C()?.fitContent();C()?.resetPriceScale()});$('#latestButton').addEventListener('click',()=>C()?.scrollToLatest());$('#shotButton').addEventListener('click',()=>C()?.exportImage());$('#fullscreenButton').addEventListener('click',()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.());
  const at=$('#autoScaleToggle'),ab=$('#autoScaleButton');ab.classList.toggle('active',app.settings.autoScale);ab.addEventListener('click',()=>{at.checked=!at.checked;at.dispatchEvent(new Event('change'))});at.addEventListener('change',()=>ab.classList.toggle('active',at.checked))
}
window.BinanceStudio={app,saveWorkspace,changeSymbol,changeTimeframe,refreshScanner};
init();
