const valid=x=>Number.isFinite(x);
export function sma(values,period=20){const out=Array(values.length).fill(null);let sum=0,count=0;for(let i=0;i<values.length;i++){const v=+values[i];if(valid(v)){sum+=v;count++}if(i>=period){const old=+values[i-period];if(valid(old)){sum-=old;count--}}if(i>=period-1&&count===period)out[i]=sum/period}return out}
export function ema(values,period=20){const out=Array(values.length).fill(null),k=2/(period+1);let seed=0,n=0,prev=null;for(let i=0;i<values.length;i++){const v=+values[i];if(!valid(v))continue;if(prev===null){seed+=v;n++;if(n===period){prev=seed/period;out[i]=prev}}else{prev=v*k+prev*(1-k);out[i]=prev}}return out}
export function rma(values,period=14){const out=Array(values.length).fill(null);let sum=0,prev=null;for(let i=0;i<values.length;i++){const v=+values[i];if(!valid(v))continue;if(prev===null){sum+=v;if(i===period-1){prev=sum/period;out[i]=prev}}else{prev=(prev*(period-1)+v)/period;out[i]=prev}}return out}
export function rsi(values,period=14){const gains=Array(values.length).fill(0),losses=Array(values.length).fill(0);for(let i=1;i<values.length;i++){const d=values[i]-values[i-1];gains[i]=Math.max(0,d);losses[i]=Math.max(0,-d)}const ag=rma(gains,period),al=rma(losses,period);return values.map((_,i)=>{if(ag[i]==null||al[i]==null)return null;if(al[i]===0)return 100;const rs=ag[i]/al[i];return 100-100/(1+rs)})}
export function atr(high,low,close,period=14){const tr=Array(close.length).fill(null);for(let i=0;i<close.length;i++){tr[i]=i===0?high[i]-low[i]:Math.max(high[i]-low[i],Math.abs(high[i]-close[i-1]),Math.abs(low[i]-close[i-1]))}return rma(tr,period)}
export function std(values,period=20){const out=Array(values.length).fill(null);for(let i=period-1;i<values.length;i++){let s=0,s2=0;for(let j=i-period+1;j<=i;j++){const v=values[j];s+=v;s2+=v*v}const m=s/period;out[i]=Math.sqrt(Math.max(0,s2/period-m*m))}return out}
export function bollinger(values,period=20,mult=2){const mid=sma(values,period),sd=std(values,period);return{mid,upper:mid.map((v,i)=>v==null?null:v+mult*sd[i]),lower:mid.map((v,i)=>v==null?null:v-mult*sd[i])}}
export function macd(values,fast=12,slow=26,signal=9){const f=ema(values,fast),s=ema(values,slow),line=values.map((_,i)=>f[i]==null||s[i]==null?null:f[i]-s[i]);const sig=ema(line.map(v=>v??NaN),signal);return{macd:line,signal:sig,hist:line.map((v,i)=>v==null||sig[i]==null?null:v-sig[i])}}
export function vwap(high,low,close,volume){const out=[];let pv=0,v=0;for(let i=0;i<close.length;i++){const tp=(high[i]+low[i]+close[i])/3;pv+=tp*volume[i];v+=volume[i];out.push(v?pv/v:null)}return out}
export function stochastic(high,low,close,kPeriod=14,dPeriod=3){const k=Array(close.length).fill(null);for(let i=kPeriod-1;i<close.length;i++){let hh=-Infinity,ll=Infinity;for(let j=i-kPeriod+1;j<=i;j++){hh=Math.max(hh,high[j]);ll=Math.min(ll,low[j])}k[i]=hh===ll?50:(close[i]-ll)/(hh-ll)*100}return{k,d:sma(k.map(x=>x??NaN),dPeriod)}}
export function highest(values,period){const o=Array(values.length).fill(null);for(let i=period-1;i<values.length;i++)o[i]=Math.max(...values.slice(i-period+1,i+1));return o}
export function lowest(values,period){const o=Array(values.length).fill(null);for(let i=period-1;i<values.length;i++)o[i]=Math.min(...values.slice(i-period+1,i+1));return o}
export function crossover(a,b,i){return i>0&&a[i]!=null&&b[i]!=null&&a[i-1]!=null&&b[i-1]!=null&&a[i]>b[i]&&a[i-1]<=b[i-1]}
export function crossunder(a,b,i){return i>0&&a[i]!=null&&b[i]!=null&&a[i-1]!=null&&b[i-1]!=null&&a[i]<b[i]&&a[i-1]>=b[i-1]}

export function wma(values,period=20){const out=Array(values.length).fill(null),den=period*(period+1)/2;for(let i=period-1;i<values.length;i++){let sum=0;for(let j=0;j<period;j++)sum+=values[i-period+1+j]*(j+1);out[i]=sum/den}return out}
export function dema(values,period=20){const e1=ema(values,period),e2=ema(e1.map(v=>v??NaN),period);return values.map((_,i)=>e1[i]==null||e2[i]==null?null:2*e1[i]-e2[i])}
export function tema(values,period=20){const e1=ema(values,period),e2=ema(e1.map(v=>v??NaN),period),e3=ema(e2.map(v=>v??NaN),period);return values.map((_,i)=>e1[i]==null||e2[i]==null||e3[i]==null?null:3*e1[i]-3*e2[i]+e3[i])}
export function roc(values,period=12){return values.map((v,i)=>i<period||!values[i-period]?null:(v/values[i-period]-1)*100)}
export function momentum(values,period=10){return values.map((v,i)=>i<period?null:v-values[i-period])}
export function obv(close,volume){const out=Array(close.length).fill(0);for(let i=1;i<close.length;i++)out[i]=out[i-1]+(close[i]>close[i-1]?volume[i]:close[i]<close[i-1]?-volume[i]:0);return out}
export function cci(high,low,close,period=20){const tp=close.map((c,i)=>(high[i]+low[i]+c)/3),ma=sma(tp,period),out=Array(close.length).fill(null);for(let i=period-1;i<close.length;i++){let dev=0;for(let j=i-period+1;j<=i;j++)dev+=Math.abs(tp[j]-ma[i]);dev/=period;out[i]=dev?(tp[i]-ma[i])/(.015*dev):0}return out}
export function williamsR(high,low,close,period=14){const out=Array(close.length).fill(null);for(let i=period-1;i<close.length;i++){let hh=-Infinity,ll=Infinity;for(let j=i-period+1;j<=i;j++){hh=Math.max(hh,high[j]);ll=Math.min(ll,low[j])}out[i]=hh===ll?-50:(hh-close[i])/(hh-ll)*-100}return out}
export function mfi(high,low,close,volume,period=14){const tp=close.map((c,i)=>(high[i]+low[i]+c)/3),out=Array(close.length).fill(null);for(let i=period;i<close.length;i++){let pos=0,neg=0;for(let j=i-period+1;j<=i;j++){const flow=tp[j]*volume[j];if(tp[j]>tp[j-1])pos+=flow;else if(tp[j]<tp[j-1])neg+=flow}out[i]=neg===0?100:100-100/(1+pos/neg)}return out}
export function cmo(values,period=14){const out=Array(values.length).fill(null);for(let i=period;i<values.length;i++){let up=0,down=0;for(let j=i-period+1;j<=i;j++){const d=values[j]-values[j-1];if(d>0)up+=d;else down-=d}out[i]=(up+down)?100*(up-down)/(up+down):0}return out}
export function donchian(high,low,period=20){const upper=highest(high,period),lower=lowest(low,period);return{upper,lower,mid:upper.map((v,i)=>v==null||lower[i]==null?null:(v+lower[i])/2)}}
export function keltner(high,low,close,period=20,mult=2){const mid=ema(close,period),a=atr(high,low,close,period);return{mid,upper:mid.map((v,i)=>v==null||a[i]==null?null:v+mult*a[i]),lower:mid.map((v,i)=>v==null||a[i]==null?null:v-mult*a[i])}}
export function adx(high,low,close,period=14){const plus=Array(close.length).fill(0),minus=Array(close.length).fill(0),tr=Array(close.length).fill(0);for(let i=1;i<close.length;i++){const up=high[i]-high[i-1],dn=low[i-1]-low[i];plus[i]=up>dn&&up>0?up:0;minus[i]=dn>up&&dn>0?dn:0;tr[i]=Math.max(high[i]-low[i],Math.abs(high[i]-close[i-1]),Math.abs(low[i]-close[i-1]))}const atrv=rma(tr,period),pdm=rma(plus,period),mdm=rma(minus,period),pdi=close.map((_,i)=>atrv[i]?100*pdm[i]/atrv[i]:null),mdi=close.map((_,i)=>atrv[i]?100*mdm[i]/atrv[i]:null),dx=close.map((_,i)=>pdi[i]!=null&&mdi[i]!=null&&(pdi[i]+mdi[i])?100*Math.abs(pdi[i]-mdi[i])/(pdi[i]+mdi[i]):null),adxv=rma(dx.map(v=>v??NaN),period);return{adx:adxv,plus:pdi,minus:mdi}}
export function supertrend(high,low,close,period=10,mult=3){const a=atr(high,low,close,period),out=Array(close.length).fill(null);let finalU=null,finalL=null,trend=1;for(let i=0;i<close.length;i++){if(a[i]==null)continue;const hl2=(high[i]+low[i])/2,bu=hl2+mult*a[i],bl=hl2-mult*a[i];finalU=i===0||finalU==null?bu:(bu<finalU||close[i-1]>finalU?bu:finalU);finalL=i===0||finalL==null?bl:(bl>finalL||close[i-1]<finalL?bl:finalL);if(trend===1&&close[i]<finalL)trend=-1;else if(trend===-1&&close[i]>finalU)trend=1;out[i]=trend===1?finalL:finalU}return out}
export function ichimoku(high,low,tenkan=9,kijun=26,senkou=52){const h9=highest(high,tenkan),l9=lowest(low,tenkan),h26=highest(high,kijun),l26=lowest(low,kijun),h52=highest(high,senkou),l52=lowest(low,senkou);return{tenkan:h9.map((v,i)=>v==null?null:(v+l9[i])/2),kijun:h26.map((v,i)=>v==null?null:(v+l26[i])/2),spanA:h26.map((_,i)=>h9[i]==null||h26[i]==null?null:((h9[i]+l9[i])/2+(h26[i]+l26[i])/2)/2),spanB:h52.map((v,i)=>v==null?null:(v+l52[i])/2)}}
export function psar(high,low,step=.02,max=.2){const n=high.length,out=Array(n).fill(null);if(n<2)return out;let bull=true,af=step,ep=high[0],sar=low[0];for(let i=1;i<n;i++){sar=sar+af*(ep-sar);if(bull){sar=Math.min(sar,low[i-1],i>1?low[i-2]:low[i-1]);if(low[i]<sar){bull=false;sar=ep;ep=low[i];af=step}else if(high[i]>ep){ep=high[i];af=Math.min(max,af+step)}}else{sar=Math.max(sar,high[i-1],i>1?high[i-2]:high[i-1]);if(high[i]>sar){bull=true;sar=ep;ep=high[i];af=step}else if(low[i]<ep){ep=low[i];af=Math.min(max,af+step)}}out[i]=sar}return out}

// --- BCS Pro Suite: independently designed indicators inspired by publicly documented premium-tool concepts. ---
const finiteOrNull=v=>Number.isFinite(v)?v:null;
const clip=(v,a,b)=>Math.max(a,Math.min(b,v));
export function rollingSum(values,period=20){const out=Array(values.length).fill(null);let s=0;for(let i=0;i<values.length;i++){const v=Number(values[i]);s+=Number.isFinite(v)?v:0;if(i>=period){const old=Number(values[i-period]);s-=Number.isFinite(old)?old:0}if(i>=period-1)out[i]=s}return out}
export function change(values){return values.map((v,i)=>i?Number(v)-Number(values[i-1]):0)}
export function zscore(values,period=50){const m=sma(values,period),sd=std(values.map(v=>Number.isFinite(v)?v:0),period);return values.map((v,i)=>m[i]==null||sd[i]==null||sd[i]===0?null:(v-m[i])/sd[i])}
export function cmf(high,low,close,volume,period=20){const mf=close.map((c,i)=>{const r=high[i]-low[i];return (r?((2*c-high[i]-low[i])/r):0)*(volume[i]||0)}),a=rollingSum(mf,period),b=rollingSum(volume,period);return close.map((_,i)=>a[i]==null||!b[i]?null:100*a[i]/b[i])}
export function vzo(close,volume,period=14){const signed=close.map((c,i)=>i===0?0:(c>close[i-1]?1:c<close[i-1]?-1:0)*(volume[i]||0)),sv=ema(signed,period),tv=ema(volume,period);return close.map((_,i)=>sv[i]==null||!tv[i]?null:100*sv[i]/tv[i])}
export function linregSlope(values,period=20){const out=Array(values.length).fill(null),sx=(period-1)*period/2,sxx=(period-1)*period*(2*period-1)/6,den=period*sxx-sx*sx;for(let i=period-1;i<values.length;i++){let sy=0,sxy=0;for(let j=0;j<period;j++){const y=Number(values[i-period+1+j]);if(!Number.isFinite(y)){sy=NaN;break}sy+=y;sxy+=j*y}if(Number.isFinite(sy))out[i]=(period*sxy-sx*sy)/den}return out}
export function supertrendState(high,low,close,period=10,mult=3){const a=atr(high,low,close,period),line=Array(close.length).fill(null),trend=Array(close.length).fill(0);let fu=null,fl=null,t=1;for(let i=0;i<close.length;i++){if(a[i]==null)continue;const mid=(high[i]+low[i])/2,bu=mid+mult*a[i],bl=mid-mult*a[i];fu=fu==null?bu:(bu<fu||close[i-1]>fu?bu:fu);fl=fl==null?bl:(bl>fl||close[i-1]<fl?bl:fl);if(t===1&&close[i]<fl){t=-1;fu=bu}else if(t===-1&&close[i]>fu){t=1;fl=bl}trend[i]=t;line[i]=t===1?fl:fu}return{line,trend,atr:a}}
export function adaptiveTrend(high,low,close,period=10,minMult=1.5,maxMult=4.5,models=7,perfLen=30){models=Math.max(3,Math.min(12,Math.round(models)));const pack=[];for(let k=0;k<models;k++){const m=minMult+(maxMult-minMult)*(models===1?0:k/(models-1)),st=supertrendState(high,low,close,period,m),perf=Array(close.length).fill(null);let p=0,alpha=2/(Math.max(2,perfLen)+1);for(let i=1;i<close.length;i++){if(st.trend[i-1]===0)continue;const atrv=st.atr[i]||Math.abs(close[i-1])*.01||1,reward=st.trend[i-1]*(close[i]-close[i-1])/atrv;p=(1-alpha)*p+alpha*reward;perf[i]=p}pack.push({m,...st,perf})}
  const bull=Array(close.length).fill(null),bear=Array(close.length).fill(null),buy=Array(close.length).fill(null),sell=Array(close.length).fill(null),confidence=Array(close.length).fill(null),chosenTrend=Array(close.length).fill(0),a=atr(high,low,close,period);
  for(let i=0;i<close.length;i++){let best=null;for(const x of pack){const score=x.perf[i];if(!Number.isFinite(x.line[i])||!Number.isFinite(score))continue;if(!best||score>best.score)best={score,line:x.line[i],trend:x.trend[i]}}if(!best)continue;chosenTrend[i]=best.trend;confidence[i]=clip(50+best.score*18,0,100);if(best.trend>0)bull[i]=best.line;else bear[i]=best.line;if(i&&chosenTrend[i]!==chosenTrend[i-1]&&chosenTrend[i-1]!==0){if(chosenTrend[i]>0)buy[i]=low[i]-(a[i]||0)*.2;else sell[i]=high[i]+(a[i]||0)*.2}}
  return{bull,bear,buy,sell,confidence,trend:chosenTrend};
}
export function reversalZones(high,low,close,period=34,atrPeriod=14,mult=2.2){const basis=ema(close,period),a=atr(high,low,close,atrPeriod),upper=Array(close.length).fill(null),lower=Array(close.length).fill(null),bull=Array(close.length).fill(null),bear=Array(close.length).fill(null);for(let i=0;i<close.length;i++){if(basis[i]==null||a[i]==null)continue;upper[i]=basis[i]+mult*a[i];lower[i]=basis[i]-mult*a[i];if(i>0&&low[i]<lower[i]&&close[i]>lower[i])bull[i]=low[i]-.15*a[i];if(i>0&&high[i]>upper[i]&&close[i]<upper[i])bear[i]=high[i]+.15*a[i]}return{basis,upper,lower,bull,bear}}
export function dynamicSR(high,low,close,volume,pivot=5,lookback=250,zoneAtr=.35){const n=close.length,sup=Array(n).fill(null),res=Array(n).fill(null),a=atr(high,low,close,14),levels=[];const add=(price,type,idx,vol)=>{const tol=(a[idx]||Math.abs(price)*.005)*zoneAtr;let hit=levels.find(x=>x.type===type&&Math.abs(x.price-price)<=tol);if(hit){const w=1+Math.log1p(vol||0);hit.price=(hit.price*hit.weight+price*w)/(hit.weight+w);hit.weight+=w;hit.last=idx;hit.touches++}else levels.push({price,type,weight:1+Math.log1p(vol||0),last:idx,touches:1});};for(let i=0;i<n;i++){const k=i-pivot;if(k>=pivot){let ph=true,pl=true;for(let j=k-pivot;j<=k+pivot;j++){if(j===k)continue;if(high[j]>=high[k])ph=false;if(low[j]<=low[k])pl=false}if(ph)add(high[k],'res',k,volume[k]);if(pl)add(low[k],'sup',k,volume[k])}for(let j=levels.length-1;j>=0;j--)if(i-levels[j].last>lookback)levels.splice(j,1);let bs=null,br=null,ss=-Infinity,sr=-Infinity;for(const x of levels){const age=i-x.last,score=x.touches*2+x.weight*.06-age/lookback;if(x.price<=close[i]&&score>ss){ss=score;bs=x}else if(x.price>close[i]&&score>sr){sr=score;br=x}}sup[i]=bs?.price??null;res[i]=br?.price??null}return{support:sup,resistance:res}}
export function structureLiquidity(high,low,close,pivot=4,toleranceAtr=.18){const n=close.length,a=atr(high,low,close,14),swingH=Array(n).fill(null),swingL=Array(n).fill(null),bosUp=Array(n).fill(null),bosDn=Array(n).fill(null),chochUp=Array(n).fill(null),chochDn=Array(n).fill(null),eqh=Array(n).fill(null),eql=Array(n).fill(null),sweepUp=Array(n).fill(null),sweepDn=Array(n).fill(null);let lastH=null,lastL=null,prevH=null,prevL=null,trend=0,brokenH=false,brokenL=false;for(let i=0;i<n;i++){const k=i-pivot;if(k>=pivot){let ph=true,pl=true;for(let j=k-pivot;j<=k+pivot;j++){if(j===k)continue;if(high[j]>=high[k])ph=false;if(low[j]<=low[k])pl=false}if(ph){prevH=lastH;lastH={price:high[k],idx:k};brokenH=false;if(prevH&&Math.abs(lastH.price-prevH.price)<=(a[k]||lastH.price*.005)*toleranceAtr)eqh[k]=high[k]}if(pl){prevL=lastL;lastL={price:low[k],idx:k};brokenL=false;if(prevL&&Math.abs(lastL.price-prevL.price)<=(a[k]||lastL.price*.005)*toleranceAtr)eql[k]=low[k]}}swingH[i]=lastH?.price??null;swingL[i]=lastL?.price??null;if(lastH&&!brokenH&&high[i]>lastH.price){if(close[i]>lastH.price){(trend<0?chochUp:bosUp)[i]=low[i]-(a[i]||0)*.15;trend=1;brokenH=true}else sweepDn[i]=high[i]+(a[i]||0)*.15}if(lastL&&!brokenL&&low[i]<lastL.price){if(close[i]<lastL.price){(trend>0?chochDn:bosDn)[i]=high[i]+(a[i]||0)*.15;trend=-1;brokenL=true}else sweepUp[i]=low[i]-(a[i]||0)*.15}}return{swingH,swingL,bosUp,bosDn,chochUp,chochDn,eqh,eql,sweepUp,sweepDn}}
export function fairValueGaps(high,low,close,maxAge=120){const n=close.length,bullTop=Array(n).fill(null),bullBot=Array(n).fill(null),bearTop=Array(n).fill(null),bearBot=Array(n).fill(null);let bull=null,bear=null;for(let i=2;i<n;i++){if(low[i]>high[i-2])bull={top:low[i],bot:high[i-2],born:i};if(high[i]<low[i-2])bear={top:low[i-2],bot:high[i],born:i};if(bull&&(low[i]<=bull.bot||i-bull.born>maxAge))bull=null;if(bear&&(high[i]>=bear.top||i-bear.born>maxAge))bear=null;if(bull){bullTop[i]=bull.top;bullBot[i]=bull.bot}if(bear){bearTop[i]=bear.top;bearBot[i]=bear.bot}}return{bullTop,bullBot,bearTop,bearBot}}
export function premiumDiscount(high,low,close,period=80,smooth=5){const hh=highest(high,period),ll=lowest(low,period),raw=close.map((c,i)=>hh[i]==null||ll[i]==null||hh[i]===ll[i]?null:200*(c-ll[i])/(hh[i]-ll[i])-100),sig=ema(raw.map(v=>v??NaN),smooth);return{raw,signal:sig}}
export function momentumFusion(high,low,close,period=14,rocPeriod=9,smooth=5){const rr=rsi(close,period).map(v=>v==null?null:(v-50)*2),st=stochastic(high,low,close,period,3).k.map(v=>v==null?null:(v-50)*2),cc=cmo(close,period),rc=roc(close,rocPeriod),z=zscore(rc.map(v=>v??0),Math.max(20,period*3)).map(v=>v==null?null:clip(v*32,-100,100)),raw=close.map((_,i)=>[rr[i],st[i],cc[i],z[i]].every(Number.isFinite)?(rr[i]+st[i]+cc[i]+z[i])/4:null),signal=ema(raw.map(v=>v??NaN),smooth);return{raw,signal}}
export function moneyFlowWave(high,low,close,volume,period=20,smooth=5){const c=cmf(high,low,close,volume,period),mf=mfi(high,low,close,volume,Math.max(5,Math.round(period*.7))).map(v=>v==null?null:(v-50)*2),rr=rsi(close,Math.max(5,Math.round(period*.7))).map(v=>v==null?null:(v-50)*2),raw=close.map((_,i)=>[c[i],mf[i],rr[i]].every(Number.isFinite)?clip(c[i]*.45+mf[i]*.35+rr[i]*.20,-100,100):null),wave=ema(raw.map(v=>v??NaN),smooth),signal=ema(wave.map(v=>v??NaN),Math.max(2,Math.round(smooth*.8)));return{wave,signal,raw}}
export function waveMomentum(high,low,close,channel=10,average=21,signal=4){const ap=close.map((c,i)=>(high[i]+low[i]+c)/3),esa=ema(ap,channel),dev=ema(ap.map((v,i)=>esa[i]==null?NaN:Math.abs(v-esa[i])),channel),ci=ap.map((v,i)=>esa[i]==null||!dev[i]?null:(v-esa[i])/(.015*dev[i])),wt1=ema(ci.map(v=>v??NaN),average),wt2=sma(wt1.map(v=>v??NaN),signal);return{wave:wt1,signal:wt2,hist:wt1.map((v,i)=>v==null||wt2[i]==null?null:v-wt2[i])}}
export function trendRibbon(close,base=8,step=5,count=8,smooth=5){count=Math.max(4,Math.min(16,Math.round(count)));const mas=[];for(let k=0;k<count;k++)mas.push(ema(close,Math.max(2,Math.round(base+k*step))));const score=Array(close.length).fill(null);for(let i=0;i<close.length;i++){let s=0,n=0;for(let k=0;k<mas.length;k++){if(mas[k][i]==null)continue;s+=close[i]>=mas[k][i]?1:-1;n++;if(k&&mas[k-1][i]!=null){s+=mas[k-1][i]>=mas[k][i]?1:-1;n++}}if(n)score[i]=100*s/n}const signal=ema(score.map(v=>v??NaN),smooth);return{score,signal}}
export function squeezeMatrix(high,low,close,period=20,bbMult=2,kcMult=1.5,momLen=20){const bb=bollinger(close,period,bbMult),kc=keltner(high,low,close,period,kcMult),a=atr(high,low,close,14),slope=linregSlope(close,momLen),momentum=slope.map((v,i)=>v==null||!a[i]?null:100*v*momLen/a[i]),on=close.map((_,i)=>bb.upper[i]!=null&&kc.upper[i]!=null&&bb.upper[i]<kc.upper[i]&&bb.lower[i]>kc.lower[i]?0:null),off=close.map((_,i)=>bb.upper[i]!=null&&kc.upper[i]!=null&&!(bb.upper[i]<kc.upper[i]&&bb.lower[i]>kc.lower[i])?0:null);return{momentum,on,off}}
export function volumePressure(close,volume,period=20,signalLen=5){const raw=vzo(close,volume,period),signal=ema(raw.map(v=>v??NaN),signalLen);return{raw,signal}}
export function atrRiskMap(high,low,close,fast=21,slow=55,atrPeriod=14,stopMult=1.5,targetR=2){const f=ema(close,fast),s=ema(close,slow),a=atr(high,low,close,atrPeriod),entry=Array(close.length).fill(null),stop=Array(close.length).fill(null),target=Array(close.length).fill(null);for(let i=0;i<close.length;i++){if(f[i]==null||s[i]==null||a[i]==null)continue;const dir=f[i]>=s[i]?1:-1;entry[i]=f[i];stop[i]=f[i]-dir*stopMult*a[i];target[i]=f[i]+dir*stopMult*targetR*a[i]}return{entry,stop,target}}
export function divergenceMatrix(high,low,close,period=14,pivot=4){const osc=rsi(close,period),bull=Array(close.length).fill(null),bear=Array(close.length).fill(null),hiddenBull=Array(close.length).fill(null),hiddenBear=Array(close.length).fill(null);let lastLow=null,lastHigh=null;for(let i=pivot*2;i<close.length;i++){const k=i-pivot;let pl=true,ph=true;for(let j=k-pivot;j<=k+pivot;j++){if(j===k)continue;if((osc[j]??Infinity)<=(osc[k]??Infinity))pl=false;if((osc[j]??-Infinity)>=(osc[k]??-Infinity))ph=false}if(pl&&Number.isFinite(osc[k])){if(lastLow){if(low[k]<lastLow.price&&osc[k]>lastLow.osc)bull[k]=osc[k];if(low[k]>lastLow.price&&osc[k]<lastLow.osc)hiddenBull[k]=osc[k]}lastLow={price:low[k],osc:osc[k]}}if(ph&&Number.isFinite(osc[k])){if(lastHigh){if(high[k]>lastHigh.price&&osc[k]<lastHigh.osc)bear[k]=osc[k];if(high[k]<lastHigh.price&&osc[k]>lastHigh.osc)hiddenBear[k]=osc[k]}lastHigh={price:high[k],osc:osc[k]}}}return{osc,bull,bear,hiddenBull,hiddenBear}}



// --- BCS Pro v1.4: additional independently implemented premium-style analytics. ---
// These algorithms use public analytical concepts only; they are not copies of proprietary vendor code.
function _ratioScore(v,min,max){if(!Number.isFinite(v)||v<min||v>max)return 0;const mid=(min+max)/2,half=Math.max(1e-9,(max-min)/2);return 1-Math.min(1,Math.abs(v-mid)/half)}
function _pivotAt(high,low,k,pivot){let ph=true,pl=true;for(let j=k-pivot;j<=k+pivot;j++){if(j===k)continue;if(high[j]>=high[k])ph=false;if(low[j]<=low[k])pl=false}return ph?'H':pl?'L':null}
export function harmonicPrzScanner(high,low,close,pivot=5,tolerance=.12,minScore=.52,maxAge=80){
  const n=close.length,a=atr(high,low,close,14),bullPrz=Array(n).fill(null),bearPrz=Array(n).fill(null),bull=Array(n).fill(null),bear=Array(n).fill(null),pivots=[];let activeBull=null,activeBear=null;
  const widened=(lo,hi)=>[Math.max(0,lo-tolerance),hi+tolerance];
  const models=[
    {ab:[.55,.70],bc:[.382,.886],cd:[1.13,1.75],xd:[.72,.86]},
    {ab:[.35,.55],bc:[.382,.886],cd:[1.50,2.80],xd:[.82,.95]},
    {ab:[.72,.84],bc:[.382,.886],cd:[1.50,2.60],xd:[1.15,1.40]},
    {ab:[.35,.68],bc:[.382,.886],cd:[2.00,3.80],xd:[1.45,1.82]}
  ];
  for(let i=0;i<n;i++){
    const k=i-pivot;if(k>=pivot&&k+pivot<n){const type=_pivotAt(high,low,k,pivot);if(type){const price=type==='H'?high[k]:low[k],last=pivots[pivots.length-1];if(last?.type===type){const moreExtreme=type==='H'?price>last.price:price<last.price;if(moreExtreme)pivots[pivots.length-1]={type,price,idx:k}}else pivots.push({type,price,idx:k});if(pivots.length>14)pivots.shift();
      if(pivots.length>=5){const q=pivots.slice(-5),types=q.map(x=>x.type).join(''),bullish=types==='LHLHL',bearish=types==='HLHLH';if(bullish||bearish){const [X,A,B,C,D]=q,xa=Math.abs(A.price-X.price),ab=Math.abs(B.price-A.price),bc=Math.abs(C.price-B.price),cd=Math.abs(D.price-C.price);if(xa>0&&ab>0&&bc>0){const rAB=ab/xa,rBC=bc/ab,rCD=cd/bc,rXD=Math.abs(D.price-X.price)/xa;let best=0;for(const m of models){const [ab0,ab1]=widened(...m.ab),[bc0,bc1]=widened(...m.bc),[cd0,cd1]=widened(...m.cd),[xd0,xd1]=widened(...m.xd);best=Math.max(best,(_ratioScore(rAB,ab0,ab1)+_ratioScore(rBC,bc0,bc1)+_ratioScore(rCD,cd0,cd1)+_ratioScore(rXD,xd0,xd1))/4)}if(best>=minScore){const pad=(a[i]||Math.abs(close[i])*.005)*.15;if(bullish){bull[i]=low[i]-pad;activeBull={price:D.price,until:i+maxAge};activeBear=null}else{bear[i]=high[i]+pad;activeBear={price:D.price,until:i+maxAge};activeBull=null}}}}}}
    }
    if(activeBull&&i<=activeBull.until)bullPrz[i]=activeBull.price;else if(activeBull&&i>activeBull.until)activeBull=null;
    if(activeBear&&i<=activeBear.until)bearPrz[i]=activeBear.price;else if(activeBear&&i>activeBear.until)activeBear=null;
  }
  return{bullPrz,bearPrz,bull,bear};
}
export function rollingRegressionLine(values,period=30){const out=Array(values.length).fill(null),sx=(period-1)*period/2,sxx=(period-1)*period*(2*period-1)/6,den=period*sxx-sx*sx;for(let i=period-1;i<values.length;i++){let sy=0,sxy=0,ok=true;for(let j=0;j<period;j++){const y=Number(values[i-period+1+j]);if(!Number.isFinite(y)){ok=false;break}sy+=y;sxy+=j*y}if(!ok)continue;const slope=(period*sxy-sx*sy)/den,intercept=(sy-slope*sx)/period;out[i]=intercept+slope*(period-1)}return out}
export function patternBreakoutRadar(high,low,close,period=34,slopeWindow=12,atrFilter=.15){const n=close.length,upper=rollingRegressionLine(high,period),lower=rollingRegressionLine(low,period),su=linregSlope(high,Math.max(4,Math.round(slopeWindow))),sl=linregSlope(low,Math.max(4,Math.round(slopeWindow))),a=atr(high,low,close,14),bull=Array(n).fill(null),bear=Array(n).fill(null);for(let i=1;i<n;i++){if(![upper[i],lower[i],su[i],sl[i],a[i]].every(Number.isFinite))continue;const spread=Math.max(1e-9,upper[i]-lower[i]),converging=su[i]<sl[i]||spread<Math.max(a[i]*period*.22,Math.abs(close[i])*.01),imp=Math.abs(close[i]-close[i-1]);if(!converging||imp<a[i]*atrFilter)continue;if(close[i]>upper[i]&&close[i-1]<=upper[i-1])bull[i]=low[i]-.2*a[i];if(close[i]<lower[i]&&close[i-1]>=lower[i-1])bear[i]=high[i]+.2*a[i]}return{upper,lower,bull,bear}}
export function institutionalImbalancePressure(open,high,low,close,volume,period=34,decay=.975,gapAtr=.12,maxAge=160){const n=close.length,a=atr(high,low,close,14),volBase=ema(volume,period),raw=Array(n).fill(null),active=[];for(let i=0;i<n;i++){for(const g of active){g.age++;g.weight*=decay;if(g.dir>0){if(low[i]<g.top)g.remaining=Math.min(g.remaining,clip((Math.max(low[i],g.bottom)-g.bottom)/(g.top-g.bottom),0,1))}else{if(high[i]>g.bottom)g.remaining=Math.min(g.remaining,clip((g.top-Math.min(high[i],g.top))/(g.top-g.bottom),0,1))}}for(let j=active.length-1;j>=0;j--)if(active[j].remaining<=.01||active[j].age>maxAge||active[j].weight<.01)active.splice(j,1);if(i>=2&&a[i]){const range=Math.max(1e-9,high[i]-low[i]),body=Math.abs(close[i]-open[i])/range,vr=volBase[i]?clip((volume[i]||0)/volBase[i],.25,4):1;if(low[i]>high[i-2]){const size=low[i]-high[i-2];if(size>=gapAtr*a[i])active.push({dir:1,bottom:high[i-2],top:low[i],remaining:1,weight:clip(size/a[i],0,4)*(0.55+.45*body)*vr,age:0})}if(high[i]<low[i-2]){const size=low[i-2]-high[i];if(size>=gapAtr*a[i])active.push({dir:-1,bottom:high[i],top:low[i-2],remaining:1,weight:clip(size/a[i],0,4)*(0.55+.45*body)*vr,age:0})}}let p=0;for(const g of active)p+=g.dir*g.weight*g.remaining;raw[i]=100*Math.tanh(p/4)}const signal=ema(raw.map(v=>v??NaN),5);return{raw,signal}}
export function orderBlockMitigationMap(open,high,low,close,volume,pivot=4,search=20,maxAge=220){const n=close.length,a=atr(high,low,close,14),bullTop=Array(n).fill(null),bullBot=Array(n).fill(null),bearTop=Array(n).fill(null),bearBot=Array(n).fill(null),bullTouch=Array(n).fill(null),bearTouch=Array(n).fill(null),zones=[];let lastH=null,lastL=null,brokenH=false,brokenL=false;for(let i=0;i<n;i++){const k=i-pivot;if(k>=pivot){const type=_pivotAt(high,low,k,pivot);if(type==='H'){lastH={price:high[k],idx:k};brokenH=false}else if(type==='L'){lastL={price:low[k],idx:k};brokenL=false}}if(lastH&&!brokenH&&close[i]>lastH.price){let src=-1;for(let j=i-1;j>=Math.max(0,i-search);j--)if(close[j]<open[j]){src=j;break}if(src>=0)zones.push({dir:1,top:Math.max(open[src],close[src]),bot:low[src],born:i,src,touches:0});brokenH=true}if(lastL&&!brokenL&&close[i]<lastL.price){let src=-1;for(let j=i-1;j>=Math.max(0,i-search);j--)if(close[j]>open[j]){src=j;break}if(src>=0)zones.push({dir:-1,top:high[src],bot:Math.min(open[src],close[src]),born:i,src,touches:0});brokenL=true}for(let z=zones.length-1;z>=0;z--){const x=zones[z];if(i-x.born>maxAge||(x.dir>0&&close[i]<x.bot)||(x.dir<0&&close[i]>x.top)){zones.splice(z,1);continue}if(i>x.born){const touched=high[i]>=x.bot&&low[i]<=x.top;if(touched&&x.lastTouch!==i){x.touches++;x.lastTouch=i;if(x.dir>0)bullTouch[i]=low[i]-(a[i]||0)*.16;else bearTouch[i]=high[i]+(a[i]||0)*.16}}}let bz=null,sz=null;for(const x of zones){if(x.dir>0&&x.top<=close[i]&&(!bz||x.top>bz.top))bz=x;if(x.dir<0&&x.bot>=close[i]&&(!sz||x.bot<sz.bot))sz=x}if(bz){bullTop[i]=bz.top;bullBot[i]=bz.bot}if(sz){bearTop[i]=sz.top;bearBot[i]=sz.bot}}return{bullTop,bullBot,bearTop,bearBot,bullTouch,bearTouch}}
export function compressionExpansionRegime(high,low,close,period=20,lookback=80,adxPeriod=14){const bb=bollinger(close,period,2),a=atr(high,low,close,14),ad=adx(high,low,close,adxPeriod).adx,slope=linregSlope(close,period),width=close.map((c,i)=>bb.upper[i]!=null&&bb.lower[i]!=null&&c?100*(bb.upper[i]-bb.lower[i])/Math.abs(c):null),atrp=close.map((c,i)=>a[i]!=null&&c?100*a[i]/Math.abs(c):null),zw=zscore(width.map(v=>v??0),lookback),za=zscore(atrp.map(v=>v??0),lookback),regime=Array(close.length).fill(null),impulse=Array(close.length).fill(null),compression=Array(close.length).fill(null),expansion=Array(close.length).fill(null);for(let i=0;i<close.length;i++){if(![zw[i],za[i],ad[i],slope[i],a[i]].every(Number.isFinite))continue;const r=clip(100*Math.tanh(zw[i]*.55+za[i]*.30+(ad[i]-25)/35*.5),-100,100);regime[i]=r;impulse[i]=r>0?clip(r*Math.sign(slope[i]),-100,100):0;if(r<-35)compression[i]=-80;if(r>35)expansion[i]=80}return{regime,impulse,compression,expansion}}
export function momentumStructureBias(high,low,close,period=14,smooth=5,threshold=24){const n=close.length,r=rsi(close,period).map(v=>v==null?null:(v-50)*2),osc=ema(r.map(v=>v??NaN),smooth),support=Array(n).fill(null),resistance=Array(n).fill(null),bull=Array(n).fill(null),bear=Array(n).fill(null),a=atr(high,low,close,14);let sup=null,res=null,lowSince=Infinity,highSince=-Infinity,bias=0;for(let i=0;i<n;i++){lowSince=Math.min(lowSince,low[i]);highSince=Math.max(highSince,high[i]);if(i&&osc[i]!=null&&osc[i-1]!=null){if(osc[i]>-threshold&&osc[i-1]<=-threshold){sup=lowSince;lowSince=low[i];if(close[i]>res&&Number.isFinite(res)){bias=1;bull[i]=low[i]-(a[i]||0)*.15}}if(osc[i]<threshold&&osc[i-1]>=threshold){res=highSince;highSince=high[i];if(close[i]<sup&&Number.isFinite(sup)){bias=-1;bear[i]=high[i]+(a[i]||0)*.15}}}if(Number.isFinite(res)&&close[i]>res&&bias<=0){bias=1;bull[i]=low[i]-(a[i]||0)*.15}if(Number.isFinite(sup)&&close[i]<sup&&bias>=0){bias=-1;bear[i]=high[i]+(a[i]||0)*.15}support[i]=Number.isFinite(sup)?sup:null;resistance[i]=Number.isFinite(res)?res:null}return{support,resistance,bull,bear,osc}}
export function projectedAtrLevels(time,high,low,close,anchorMinutes=240,period=10,mult=1){const n=close.length,upper=Array(n).fill(null),lower=Array(n).fill(null),anchorOpen=Array(n).fill(null),groupMs=Math.max(1,anchorMinutes)*60000,trs=[];let key=null,gOpen=null,gHigh=null,gLow=null,gClose=null,prevClose=null,atrRef=null;const finalize=()=>{if(gHigh==null)return;const tr=prevClose==null?gHigh-gLow:Math.max(gHigh-gLow,Math.abs(gHigh-prevClose),Math.abs(gLow-prevClose));trs.push(tr);if(trs.length>period)trs.shift();if(trs.length===period)atrRef=trs.reduce((a,b)=>a+b,0)/period;prevClose=gClose};for(let i=0;i<n;i++){let t=Number(time?.[i]??i*60000);if(t<1e12)t*=1000;const k=Math.floor(t/groupMs);if(key===null||k!==key){if(key!==null)finalize();key=k;gOpen=close[i];gHigh=high[i];gLow=low[i];gClose=close[i]}else{gHigh=Math.max(gHigh,high[i]);gLow=Math.min(gLow,low[i]);gClose=close[i]}anchorOpen[i]=gOpen;if(atrRef!=null){upper[i]=gLow+atrRef*mult;lower[i]=gHigh-atrRef*mult}}return{upper,lower,anchorOpen}}
export function demandSupplyZoneEngine(open,high,low,close,volume,baseMax=4,baseRatio=.38,impulseAtr=1.25,maxAge=260){const n=close.length,a=atr(high,low,close,14),dTop=Array(n).fill(null),dBot=Array(n).fill(null),sTop=Array(n).fill(null),sBot=Array(n).fill(null),dTest=Array(n).fill(null),sTest=Array(n).fill(null),zones=[];for(let i=2;i<n;i++){if(!a[i])continue;let start=i-1,count=0;while(start>=0&&count<baseMax){const range=Math.max(1e-9,high[start]-low[start]),body=Math.abs(close[start]-open[start]);if(body/range>baseRatio||range>a[i]*1.15)break;count++;start--}if(count){const b0=i-count,b1=i-1,baseHigh=Math.max(...high.slice(b0,b1+1)),baseLow=Math.min(...low.slice(b0,b1+1)),bodyHigh=Math.max(...open.slice(b0,b1+1),...close.slice(b0,b1+1)),bodyLow=Math.min(...open.slice(b0,b1+1),...close.slice(b0,b1+1)),impulse=Math.abs(close[i]-open[i]);if(impulse>=impulseAtr*a[i]&&close[i]>baseHigh)zones.push({dir:1,top:bodyHigh,bot:baseLow,born:i,touches:0});if(impulse>=impulseAtr*a[i]&&close[i]<baseLow)zones.push({dir:-1,top:baseHigh,bot:bodyLow,born:i,touches:0})}for(let z=zones.length-1;z>=0;z--){const x=zones[z];if(i-x.born>maxAge||(x.dir>0&&close[i]<x.bot)||(x.dir<0&&close[i]>x.top)){zones.splice(z,1);continue}if(i>x.born&&high[i]>=x.bot&&low[i]<=x.top&&x.lastTouch!==i){x.touches++;x.lastTouch=i;if(x.dir>0)dTest[i]=low[i]-.15*a[i];else sTest[i]=high[i]+.15*a[i]}}let dz=null,sz=null;for(const x of zones){if(x.dir>0&&x.top<=close[i]&&(!dz||x.top>dz.top))dz=x;if(x.dir<0&&x.bot>=close[i]&&(!sz||x.bot<sz.bot))sz=x}if(dz){dTop[i]=dz.top;dBot[i]=dz.bot}if(sz){sTop[i]=sz.top;sBot[i]=sz.bot}}return{dTop,dBot,sTop,sBot,dTest,sTest}}
export function weightedCurveChannel(high,low,close,fast=12,mid=34,slow=89,wFast=.5,wMid=.3,wSlow=.2,atrPeriod=14,mult=1.8){const f=ema(close,fast),m=wma(close,mid),s=tema(close,slow),a=atr(high,low,close,atrPeriod),curve=Array(close.length).fill(null),upper=Array(close.length).fill(null),lower=Array(close.length).fill(null);const den=Math.max(1e-9,wFast+wMid+wSlow);for(let i=0;i<close.length;i++){if(![f[i],m[i],s[i],a[i]].every(Number.isFinite))continue;curve[i]=(f[i]*wFast+m[i]*wMid+s[i]*wSlow)/den;upper[i]=curve[i]+mult*a[i];lower[i]=curve[i]-mult*a[i]}return{curve,upper,lower}}
export function rollingVolumeProfile(high,low,close,volume,window=120,bins=24,valueArea=70){window=Math.max(20,Math.round(window));bins=Math.max(8,Math.min(64,Math.round(bins)));const n=close.length,poc=Array(n).fill(null),vah=Array(n).fill(null),val=Array(n).fill(null);for(let i=window-1;i<n;i++){let lo=Infinity,hi=-Infinity;for(let j=i-window+1;j<=i;j++){lo=Math.min(lo,low[j]);hi=Math.max(hi,high[j])}const span=hi-lo;if(!(span>0))continue;const bucket=Array(bins).fill(0);for(let j=i-window+1;j<=i;j++){const tp=(high[j]+low[j]+close[j])/3,k=Math.max(0,Math.min(bins-1,Math.floor((tp-lo)/span*bins)));bucket[k]+=Math.max(0,volume[j]||0)}let p=0;for(let k=1;k<bins;k++)if(bucket[k]>bucket[p])p=k;const total=bucket.reduce((a,b)=>a+b,0),target=total*clip(valueArea,1,99)/100;let acc=bucket[p],l=p,h=p;while(acc<target&&(l>0||h<bins-1)){const lv=l>0?bucket[l-1]:-1,hv=h<bins-1?bucket[h+1]:-1;if(hv>lv){h++;acc+=bucket[h]}else{l--;acc+=bucket[l]}}const step=span/bins;poc[i]=lo+(p+.5)*step;val[i]=lo+l*step;vah[i]=lo+(h+1)*step}return{poc,vah,val}}

export const BUILT_INS={
  EMA:{id:'ema',name:'Exponential Moving Average',overlay:true,defaults:{period:20},compute:(d,p)=>[{name:`EMA ${p.period}`,values:ema(d.close,p.period)}]},
  SMA:{id:'sma',name:'Simple Moving Average',overlay:true,defaults:{period:20},compute:(d,p)=>[{name:`SMA ${p.period}`,values:sma(d.close,p.period)}]},
  WMA:{id:'wma',name:'Weighted Moving Average',overlay:true,defaults:{period:20},compute:(d,p)=>[{name:`WMA ${p.period}`,values:wma(d.close,p.period)}]},
  DEMA:{id:'dema',name:'Double EMA',overlay:true,defaults:{period:20},compute:(d,p)=>[{name:`DEMA ${p.period}`,values:dema(d.close,p.period)}]},
  TEMA:{id:'tema',name:'Triple EMA',overlay:true,defaults:{period:20},compute:(d,p)=>[{name:`TEMA ${p.period}`,values:tema(d.close,p.period)}]},
  BOLL:{id:'bollinger',name:'Bollinger Bands',overlay:true,defaults:{period:20,mult:2},compute:(d,p)=>{const b=bollinger(d.close,p.period,p.mult);return[{name:'BB Upper',values:b.upper},{name:'BB Basis',values:b.mid},{name:'BB Lower',values:b.lower}]}},
  VWAP:{id:'vwap',name:'VWAP',overlay:true,defaults:{},compute:d=>[{name:'VWAP',values:vwap(d.high,d.low,d.close,d.volume)}]},
  DONCH:{id:'donchian',name:'Donchian Channels',overlay:true,defaults:{period:20},compute:(d,p)=>{const x=donchian(d.high,d.low,p.period);return[{name:'DC Upper',values:x.upper},{name:'DC Mid',values:x.mid},{name:'DC Lower',values:x.lower}]}},
  KELT:{id:'keltner',name:'Keltner Channels',overlay:true,defaults:{period:20,mult:2},compute:(d,p)=>{const x=keltner(d.high,d.low,d.close,p.period,p.mult);return[{name:'KC Upper',values:x.upper},{name:'KC Mid',values:x.mid},{name:'KC Lower',values:x.lower}]}},
  SUPERT:{id:'supertrend',name:'Supertrend',overlay:true,defaults:{period:10,mult:3},compute:(d,p)=>[{name:'Supertrend',values:supertrend(d.high,d.low,d.close,p.period,p.mult)}]},
  ICHI:{id:'ichimoku',name:'Ichimoku Cloud',overlay:true,defaults:{tenkan:9,kijun:26,senkou:52},compute:(d,p)=>{const x=ichimoku(d.high,d.low,p.tenkan,p.kijun,p.senkou);return[{name:'Tenkan',values:x.tenkan},{name:'Kijun',values:x.kijun},{name:'Span A',values:x.spanA},{name:'Span B',values:x.spanB}]}},
  PSAR:{id:'psar',name:'Parabolic SAR',overlay:true,defaults:{step:.02,max:.2},compute:(d,p)=>[{name:'PSAR',values:psar(d.high,d.low,p.step,p.max)}]},
  RSI:{id:'rsi',name:'Relative Strength Index',overlay:false,scale:{min:0,max:100,levels:[30,50,70]},defaults:{period:14},compute:(d,p)=>[{name:`RSI ${p.period}`,values:rsi(d.close,p.period)}]},
  MACD:{id:'macd',name:'MACD',overlay:false,defaults:{fast:12,slow:26,signal:9},compute:(d,p)=>{const m=macd(d.close,p.fast,p.slow,p.signal);return[{name:'MACD',values:m.macd},{name:'Signal',values:m.signal},{name:'Histogram',values:m.hist,type:'histogram'}]}},
  ATR:{id:'atr',name:'Average True Range',overlay:false,defaults:{period:14},compute:(d,p)=>[{name:`ATR ${p.period}`,values:atr(d.high,d.low,d.close,p.period)}]},
  STOCH:{id:'stoch',name:'Stochastic',overlay:false,scale:{min:0,max:100,levels:[20,50,80]},defaults:{k:14,d:3},compute:(d,p)=>{const x=stochastic(d.high,d.low,d.close,p.k,p.d);return[{name:'%K',values:x.k},{name:'%D',values:x.d}]}},
  ADX:{id:'adx',name:'Average Directional Index',overlay:false,scale:{min:0,max:100,levels:[20,25,50]},defaults:{period:14},compute:(d,p)=>{const x=adx(d.high,d.low,d.close,p.period);return[{name:'ADX',values:x.adx},{name:'+DI',values:x.plus},{name:'-DI',values:x.minus}]}},
  CCI:{id:'cci',name:'Commodity Channel Index',overlay:false,scale:{min:-250,max:250,levels:[-100,0,100]},defaults:{period:20},compute:(d,p)=>[{name:'CCI',values:cci(d.high,d.low,d.close,p.period)}]},
  MFI:{id:'mfi',name:'Money Flow Index',overlay:false,scale:{min:0,max:100,levels:[20,50,80]},defaults:{period:14},compute:(d,p)=>[{name:'MFI',values:mfi(d.high,d.low,d.close,d.volume,p.period)}]},
  WILLR:{id:'williamsr',name:'Williams %R',overlay:false,scale:{min:-100,max:0,levels:[-80,-50,-20]},defaults:{period:14},compute:(d,p)=>[{name:'Williams %R',values:williamsR(d.high,d.low,d.close,p.period)}]},
  ROC:{id:'roc',name:'Rate of Change',overlay:false,defaults:{period:12},compute:(d,p)=>[{name:'ROC',values:roc(d.close,p.period)}]},
  MOM:{id:'momentum',name:'Momentum',overlay:false,defaults:{period:10},compute:(d,p)=>[{name:'Momentum',values:momentum(d.close,p.period)}]},
  OBV:{id:'obv',name:'On Balance Volume',overlay:false,defaults:{},compute:d=>[{name:'OBV',values:obv(d.close,d.volume)}]},
  CMO:{id:'cmo',name:'Chande Momentum Oscillator',overlay:false,scale:{min:-100,max:100,levels:[-50,0,50]},defaults:{period:14},compute:(d,p)=>[{name:'CMO',values:cmo(d.close,p.period)}]},
  PRO_ADAPT:{id:'pro_adaptive_trend',name:'BCS Pro — Adaptive Trend Signals',category:'BCS Pro Suite',overlay:true,defaults:{period:10,minMult:1.5,maxMult:4.5,models:7,perfLen:30},compute:(d,p)=>{const x=adaptiveTrend(d.high,d.low,d.close,p.period,p.minMult,p.maxMult,p.models,p.perfLen);return[{name:'Bull Trail',values:x.bull,color:'#18b982'},{name:'Bear Trail',values:x.bear,color:'#f05252'},{name:'Buy',values:x.buy,type:'triangleUp',color:'#18b982'},{name:'Sell',values:x.sell,type:'triangleDown',color:'#f05252'}]}},
  PRO_ADAPT_CONF:{id:'pro_adaptive_confidence',name:'BCS Pro — Adaptive Trend Confidence',category:'BCS Pro Suite',overlay:false,scale:{min:0,max:100,levels:[25,50,75]},defaults:{period:10,minMult:1.5,maxMult:4.5,models:7,perfLen:30},compute:(d,p)=>{const x=adaptiveTrend(d.high,d.low,d.close,p.period,p.minMult,p.maxMult,p.models,p.perfLen);return[{name:'Confidence',values:x.confidence,color:'#4c7dff'}]}},
  PRO_REV:{id:'pro_reversal_zones',name:'BCS Pro — Reversal Zones',category:'BCS Pro Suite',overlay:true,defaults:{period:34,atrPeriod:14,mult:2.2},compute:(d,p)=>{const x=reversalZones(d.high,d.low,d.close,p.period,p.atrPeriod,p.mult);return[{name:'Upper Reversal Zone',values:x.upper,color:'#f05252'},{name:'Basis',values:x.basis,color:'#8b98a9'},{name:'Lower Reversal Zone',values:x.lower,color:'#18b982'},{name:'Bull Reversal',values:x.bull,type:'triangleUp',color:'#18b982'},{name:'Bear Reversal',values:x.bear,type:'triangleDown',color:'#f05252'}]}},
  PRO_DSR:{id:'pro_dynamic_sr',name:'BCS Pro — Dynamic Support / Resistance',category:'BCS Pro Suite',overlay:true,defaults:{pivot:5,lookback:250,zoneAtr:.35},compute:(d,p)=>{const x=dynamicSR(d.high,d.low,d.close,d.volume,p.pivot,p.lookback,p.zoneAtr);return[{name:'Dynamic Resistance',values:x.resistance,type:'step',color:'#f05252'},{name:'Dynamic Support',values:x.support,type:'step',color:'#18b982'}]}},
  PRO_STRUCTURE:{id:'pro_structure_liquidity',name:'BCS Pro — Market Structure & Liquidity',category:'BCS Pro Suite',overlay:true,defaults:{pivot:4,toleranceAtr:.18},compute:(d,p)=>{const x=structureLiquidity(d.high,d.low,d.close,p.pivot,p.toleranceAtr);return[{name:'Swing High',values:x.swingH,type:'step',color:'#f0a24a'},{name:'Swing Low',values:x.swingL,type:'step',color:'#50c7e8'},{name:'Bull BOS',values:x.bosUp,type:'triangleUp',color:'#18b982'},{name:'Bear BOS',values:x.bosDn,type:'triangleDown',color:'#f05252'},{name:'Bull CHoCH',values:x.chochUp,type:'triangleUp',color:'#4c7dff'},{name:'Bear CHoCH',values:x.chochDn,type:'triangleDown',color:'#d66efd'},{name:'Equal High',values:x.eqh,type:'points',color:'#f6c453'},{name:'Equal Low',values:x.eql,type:'points',color:'#f6c453'},{name:'Bull Liquidity Sweep',values:x.sweepUp,type:'triangleUp',color:'#2dd4bf'},{name:'Bear Liquidity Sweep',values:x.sweepDn,type:'triangleDown',color:'#fb7185'}]}},
  PRO_FVG:{id:'pro_fvg_map',name:'BCS Pro — Fair Value Gap Map',category:'BCS Pro Suite',overlay:true,defaults:{maxAge:120},compute:(d,p)=>{const x=fairValueGaps(d.high,d.low,d.close,p.maxAge);return[{name:'Bull FVG Top',values:x.bullTop,type:'step',color:'#18b982'},{name:'Bull FVG Bottom',values:x.bullBot,type:'step',color:'#18b982'},{name:'Bear FVG Top',values:x.bearTop,type:'step',color:'#f05252'},{name:'Bear FVG Bottom',values:x.bearBot,type:'step',color:'#f05252'}]}},
  PRO_PD:{id:'pro_premium_discount',name:'BCS Pro — Premium / Discount Oscillator',category:'BCS Pro Suite',overlay:false,scale:{min:-100,max:100,levels:[-50,0,50]},defaults:{period:80,smooth:5},compute:(d,p)=>{const x=premiumDiscount(d.high,d.low,d.close,p.period,p.smooth);return[{name:'Premium / Discount',values:x.raw,color:'#4c7dff'},{name:'Signal',values:x.signal,color:'#f6c453'}]}},
  PRO_MOM:{id:'pro_momentum_matrix',name:'BCS Pro — Momentum Matrix',category:'BCS Pro Suite',overlay:false,scale:{min:-100,max:100,levels:[-60,0,60]},defaults:{period:14,rocPeriod:9,smooth:5},compute:(d,p)=>{const x=momentumFusion(d.high,d.low,d.close,p.period,p.rocPeriod,p.smooth);return[{name:'Momentum Fusion',values:x.raw,color:'#4c7dff'},{name:'Signal',values:x.signal,color:'#f6c453'}]}},
  PRO_MFLOW:{id:'pro_money_flow_wave',name:'BCS Pro — Money Flow Wave',category:'BCS Pro Suite',overlay:false,scale:{min:-100,max:100,levels:[-50,0,50]},defaults:{period:20,smooth:5},compute:(d,p)=>{const x=moneyFlowWave(d.high,d.low,d.close,d.volume,p.period,p.smooth);return[{name:'Money Flow Wave',values:x.wave,color:'#18b982'},{name:'Signal',values:x.signal,color:'#f6c453'},{name:'Flow Pressure',values:x.raw,type:'histogram'}]}},
  PRO_WAVE:{id:'pro_wave_momentum',name:'BCS Pro — Wave Momentum',category:'BCS Pro Suite',overlay:false,scale:{min:-100,max:100,levels:[-60,0,60]},defaults:{channel:10,average:21,signal:4},compute:(d,p)=>{const x=waveMomentum(d.high,d.low,d.close,p.channel,p.average,p.signal);return[{name:'Wave',values:x.wave,color:'#4c7dff'},{name:'Signal',values:x.signal,color:'#f6c453'},{name:'Wave Delta',values:x.hist,type:'histogram'}]}},
  PRO_RIBBON:{id:'pro_trend_ribbon',name:'BCS Pro — Composite Trend Ribbon',category:'BCS Pro Suite',overlay:false,scale:{min:-100,max:100,levels:[-50,0,50]},defaults:{base:8,step:5,count:8,smooth:5},compute:(d,p)=>{const x=trendRibbon(d.close,p.base,p.step,p.count,p.smooth);return[{name:'Ribbon Score',values:x.score,color:'#4c7dff'},{name:'Signal',values:x.signal,color:'#f6c453'}]}},
  PRO_SQUEEZE:{id:'pro_squeeze_matrix',name:'BCS Pro — Volatility Squeeze Matrix',category:'BCS Pro Suite',overlay:false,defaults:{period:20,bbMult:2,kcMult:1.5,momLen:20},compute:(d,p)=>{const x=squeezeMatrix(d.high,d.low,d.close,p.period,p.bbMult,p.kcMult,p.momLen);return[{name:'Squeeze Momentum',values:x.momentum,type:'histogram'},{name:'Squeeze On',values:x.on,type:'points',color:'#f05252'},{name:'Squeeze Off',values:x.off,type:'points',color:'#18b982'}]}},
  PRO_VPRESS:{id:'pro_volume_pressure',name:'BCS Pro — Volume Pressure',category:'BCS Pro Suite',overlay:false,scale:{min:-100,max:100,levels:[-40,0,40]},defaults:{period:20,signal:5},compute:(d,p)=>{const x=volumePressure(d.close,d.volume,p.period,p.signal);return[{name:'Volume Pressure',values:x.raw,color:'#2dd4bf'},{name:'Signal',values:x.signal,color:'#f6c453'}]}},
  PRO_RISK:{id:'pro_atr_risk_map',name:'BCS Pro — ATR Risk Map',category:'BCS Pro Suite',overlay:true,defaults:{fast:21,slow:55,atrPeriod:14,stopMult:1.5,targetR:2},compute:(d,p)=>{const x=atrRiskMap(d.high,d.low,d.close,p.fast,p.slow,p.atrPeriod,p.stopMult,p.targetR);return[{name:'Entry Bias',values:x.entry,color:'#4c7dff'},{name:'Dynamic Stop',values:x.stop,color:'#f05252'},{name:'Target',values:x.target,color:'#18b982'}]}},
  PRO_DIV:{id:'pro_divergence_matrix',name:'BCS Pro — Momentum Divergence Matrix',category:'BCS Pro Suite',overlay:false,scale:{min:0,max:100,levels:[30,50,70]},defaults:{period:14,pivot:4},compute:(d,p)=>{const x=divergenceMatrix(d.high,d.low,d.close,p.period,p.pivot);return[{name:'Momentum',values:x.osc,color:'#4c7dff'},{name:'Bullish Regular',values:x.bull,type:'triangleUp',color:'#18b982'},{name:'Bearish Regular',values:x.bear,type:'triangleDown',color:'#f05252'},{name:'Bullish Hidden',values:x.hiddenBull,type:'triangleUp',color:'#2dd4bf'},{name:'Bearish Hidden',values:x.hiddenBear,type:'triangleDown',color:'#d66efd'}]}},
  PRO_HARMONIC:{id:'pro_harmonic_prz',name:'BCS Pro — Harmonic PRZ Scanner',category:'BCS Pro Suite',overlay:true,defaults:{pivot:5,tolerance:.12,minScore:.52,maxAge:80},compute:(d,p)=>{const x=harmonicPrzScanner(d.high,d.low,d.close,p.pivot,p.tolerance,p.minScore,p.maxAge);return[{name:'Bullish PRZ',values:x.bullPrz,type:'step',color:'#18b982'},{name:'Bearish PRZ',values:x.bearPrz,type:'step',color:'#f05252'},{name:'Bull Pattern',values:x.bull,type:'triangleUp',color:'#18b982'},{name:'Bear Pattern',values:x.bear,type:'triangleDown',color:'#f05252'}]}},
  PRO_PATTERN_RADAR:{id:'pro_pattern_breakout_radar',name:'BCS Pro — Pattern Breakout Radar',category:'BCS Pro Suite',overlay:true,defaults:{period:34,slopeWindow:12,atrFilter:.15},compute:(d,p)=>{const x=patternBreakoutRadar(d.high,d.low,d.close,p.period,p.slopeWindow,p.atrFilter);return[{name:'Pattern Upper',values:x.upper,color:'#f0a24a'},{name:'Pattern Lower',values:x.lower,color:'#50c7e8'},{name:'Bull Breakout',values:x.bull,type:'triangleUp',color:'#18b982'},{name:'Bear Breakout',values:x.bear,type:'triangleDown',color:'#f05252'}]}},
  PRO_IIP:{id:'pro_institutional_imbalance_pressure',name:'BCS Pro — Institutional Imbalance Pressure',category:'BCS Pro Suite',overlay:false,scale:{min:-100,max:100,levels:[-60,0,60]},defaults:{period:34,decay:.975,gapAtr:.12,maxAge:160},compute:(d,p)=>{const x=institutionalImbalancePressure(d.open,d.high,d.low,d.close,d.volume,p.period,p.decay,p.gapAtr,p.maxAge);return[{name:'Imbalance Pressure',values:x.raw,type:'histogram'},{name:'Pressure Signal',values:x.signal,color:'#f6c453'}]}},
  PRO_OBM:{id:'pro_order_block_mitigation',name:'BCS Pro — Order Block Mitigation Map',category:'BCS Pro Suite',overlay:true,defaults:{pivot:4,search:20,maxAge:220},compute:(d,p)=>{const x=orderBlockMitigationMap(d.open,d.high,d.low,d.close,d.volume,p.pivot,p.search,p.maxAge);return[{name:'Bull OB Top',values:x.bullTop,type:'step',color:'#18b982'},{name:'Bull OB Bottom',values:x.bullBot,type:'step',color:'#18b982'},{name:'Bear OB Top',values:x.bearTop,type:'step',color:'#f05252'},{name:'Bear OB Bottom',values:x.bearBot,type:'step',color:'#f05252'},{name:'Bull Mitigation',values:x.bullTouch,type:'triangleUp',color:'#2dd4bf'},{name:'Bear Mitigation',values:x.bearTouch,type:'triangleDown',color:'#fb7185'}]}},
  PRO_REGIME:{id:'pro_compression_expansion_regime',name:'BCS Pro — Compression / Expansion Regime',category:'BCS Pro Suite',overlay:false,scale:{min:-100,max:100,levels:[-35,0,35]},defaults:{period:20,lookback:80,adxPeriod:14},compute:(d,p)=>{const x=compressionExpansionRegime(d.high,d.low,d.close,p.period,p.lookback,p.adxPeriod);return[{name:'Regime',values:x.regime,color:'#4c7dff'},{name:'Directional Impulse',values:x.impulse,type:'histogram'},{name:'Compression',values:x.compression,type:'points',color:'#f6c453'},{name:'Expansion',values:x.expansion,type:'points',color:'#18b982'}]}},
  PRO_MSTRUCT:{id:'pro_momentum_structure_bias',name:'BCS Pro — Momentum Structure Bias',category:'BCS Pro Suite',overlay:true,defaults:{period:14,smooth:5,threshold:24},compute:(d,p)=>{const x=momentumStructureBias(d.high,d.low,d.close,p.period,p.smooth,p.threshold);return[{name:'Momentum Support',values:x.support,type:'step',color:'#18b982'},{name:'Momentum Resistance',values:x.resistance,type:'step',color:'#f05252'},{name:'Bull Bias Flip',values:x.bull,type:'triangleUp',color:'#18b982'},{name:'Bear Bias Flip',values:x.bear,type:'triangleDown',color:'#f05252'}]}},
  PRO_ATR_LEVELS:{id:'pro_projected_atr_levels',name:'BCS Pro — Projected ATR Volatility Levels',category:'BCS Pro Suite',overlay:true,defaults:{anchorMinutes:240,period:10,mult:1},compute:(d,p)=>{const x=projectedAtrLevels(d.time,d.high,d.low,d.close,p.anchorMinutes,p.period,p.mult);return[{name:'ATR Upper',values:x.upper,type:'step',color:'#f05252'},{name:'ATR Lower',values:x.lower,type:'step',color:'#18b982'},{name:'Anchor Open',values:x.anchorOpen,type:'step',color:'#8b98a9'}]}},
  PRO_DS_ZONE:{id:'pro_demand_supply_zone_engine',name:'BCS Pro — Demand / Supply Zone Engine',category:'BCS Pro Suite',overlay:true,defaults:{baseMax:4,baseRatio:.38,impulseAtr:1.25,maxAge:260},compute:(d,p)=>{const x=demandSupplyZoneEngine(d.open,d.high,d.low,d.close,d.volume,p.baseMax,p.baseRatio,p.impulseAtr,p.maxAge);return[{name:'Demand Proximal',values:x.dTop,type:'step',color:'#18b982'},{name:'Demand Distal',values:x.dBot,type:'step',color:'#18b982'},{name:'Supply Distal',values:x.sTop,type:'step',color:'#f05252'},{name:'Supply Proximal',values:x.sBot,type:'step',color:'#f05252'},{name:'Demand Test',values:x.dTest,type:'triangleUp',color:'#2dd4bf'},{name:'Supply Test',values:x.sTest,type:'triangleDown',color:'#fb7185'}]}},
  PRO_CURVE:{id:'pro_weighted_curve_channel',name:'BCS Pro — Weighted Curve Channel',category:'BCS Pro Suite',overlay:true,defaults:{fast:12,mid:34,slow:89,wFast:.5,wMid:.3,wSlow:.2,atrPeriod:14,mult:1.8},compute:(d,p)=>{const x=weightedCurveChannel(d.high,d.low,d.close,p.fast,p.mid,p.slow,p.wFast,p.wMid,p.wSlow,p.atrPeriod,p.mult);return[{name:'Weighted Curve',values:x.curve,color:'#4c7dff'},{name:'Curve Upper',values:x.upper,color:'#f0a24a'},{name:'Curve Lower',values:x.lower,color:'#50c7e8'}]}},
  PRO_VPROFILE:{id:'pro_rolling_volume_profile',name:'BCS Pro — Rolling Volume Profile Map',category:'BCS Pro Suite',overlay:true,defaults:{window:120,bins:24,valueArea:70},compute:(d,p)=>{const x=rollingVolumeProfile(d.high,d.low,d.close,d.volume,p.window,p.bins,p.valueArea);return[{name:'POC',values:x.poc,color:'#f6c453'},{name:'VAH',values:x.vah,color:'#f05252'},{name:'VAL',values:x.val,color:'#18b982'}]}}

};
